import type{Metadata}from"next";
import{redirect}from"next/navigation";
import{ChartCard,DashboardShell,DataTable,EmptyState,StatCard}from"@/src/components/dashboard/dashboard-shell";
import{createSupabaseServerClient}from"@/src/lib/supabase/server";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Platform analytics",robots:{index:false,follow:false}};
export default async function AdminAnalytics({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
  const params=await searchParams,supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/login?returnTo=/admin/analytics");const{data:allowed}=await supabase.rpc("has_permission",{required_permission:"analytics.read"});if(!allowed)redirect("/admin");
  const today=new Date(),monthStart=new Date();monthStart.setDate(monthStart.getDate()-29);const to=params.to||today.toISOString().slice(0,10),from=params.from||monthStart.toISOString().slice(0,10);
  const{data:rows}=await supabase.from("analytics_daily").select("day,entity_type,event_type,event_count").gte("day",from).lte("day",to);const all=rows||[],total=(event:string)=>all.filter((row)=>row.event_type===event).reduce((sum,row)=>sum+Number(row.event_count),0);const byEvent=Object.entries(all.reduce<Record<string,number>>((acc,row)=>({...acc,[row.event_type]:(acc[row.event_type]||0)+Number(row.event_count)}),{})).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...byEvent.map(([,count])=>count));
  return <DashboardShell variant="admin" title="Platform analytics" description="Aggregated, privacy-safe engagement across public experiences." breadcrumbs={[{label:"Admin",href:"/admin"},{label:"Analytics"}]}><form className="filter-bar"><label>From <input name="from" type="date" defaultValue={from}/></label><label>To <input name="to" type="date" defaultValue={to}/></label><button className="button button-small">Apply</button></form><section className="dashboard-stat-grid"><StatCard label="Listing views" value={total("listing_view")}/><StatCard label="Search impressions" value={total("search_impression")}/><StatCard label="Enquiries submitted" value={total("enquiry_submitted")}/><StatCard label="Contact clicks" value={total("phone_click")+total("whatsapp_click")}/></section><section className="dashboard-section"><ChartCard title="Event distribution"><div className="chart-bars">{byEvent.map(([event,count])=><div key={event}><i style={{height:`${count/max*100}%`}}/><small>{event.slice(0,10)}</small></div>)}</div></ChartCard></section><section className="dashboard-section">{byEvent.length?<DataTable caption="Analytics event totals" headers={["Event","Count"]}>{byEvent.map(([event,count])=><tr key={event}><td>{event.replaceAll("_"," ")}</td><td>{count}</td></tr>)}</DataTable>:<EmptyState title="No aggregated data" description="Run daily analytics aggregation after events are collected."/>}</section></DashboardShell>
}
