import type {Metadata} from "next";
import Link from "next/link";
import {redirect} from "next/navigation";
import {AdminNavigation} from "@/src/components/admin-navigation";
import {env} from "@/src/lib/env";
import {PERMISSIONS,hasPermission} from "@/src/lib/auth/permissions";
import {logEvent} from "@/src/lib/observability/logger";
import {createSupabaseServerClient} from "@/src/lib/supabase/server";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Admin operations",robots:{index:false,follow:false}};
function monthKey(value:string){const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`}
const emptyCount={count:null,data:null,error:null};const emptyRows={data:[] as {created_at:string}[],error:null};

export default async function AdminPage(){
  if(!env.isSupabaseConfigured)return <main id="main" className="portal-page"><div className="shell"><div className="config-warning"><h1>Admin configuration pending</h1><p>Apply the Supabase migrations and promote the first administrator.</p></div></div></main>;
  const supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/login?returnTo=/admin");const{data:context,error:contextError}=await supabase.rpc("get_current_auth_context");if(contextError||!context){logEvent("error","admin.authorization_context_failed",{code:contextError?.code||"context_missing"});return <AdminFailure/>}
  const canProperties=hasPermission(context,PERMISSIONS.propertiesRead),canEnquiries=hasPermission(context,PERMISSIONS.enquiriesRead),canUsers=hasPermission(context,PERMISSIONS.usersRead),canAudit=hasPermission(context,PERMISSIONS.auditRead);if(!canProperties&&!canEnquiries&&!canUsers&&!canAudit)redirect("/dashboard?error=admin_role_required");
  const startToday=new Date();startToday.setHours(0,0,0,0);const startYear=new Date();startYear.setMonth(startYear.getMonth()-11,1);startYear.setHours(0,0,0,0);
  const [users,total,pending,published,drafts,rejected,todayEnquiries,totalEnquiries,listingsSeries,enquirySeries,activity]=await Promise.all([
    canUsers?supabase.from("profiles").select("id",{count:"exact",head:true}):Promise.resolve(emptyCount),
    canProperties?supabase.from("properties").select("id",{count:"exact",head:true}).is("deleted_at",null):Promise.resolve(emptyCount),
    canProperties?supabase.from("properties").select("id",{count:"exact",head:true}).eq("status","pending_review"):Promise.resolve(emptyCount),
    canProperties?supabase.from("properties").select("id",{count:"exact",head:true}).eq("status","published"):Promise.resolve(emptyCount),
    canProperties?supabase.from("properties").select("id",{count:"exact",head:true}).eq("status","draft"):Promise.resolve(emptyCount),
    canProperties?supabase.from("properties").select("id",{count:"exact",head:true}).eq("status","rejected"):Promise.resolve(emptyCount),
    canEnquiries?supabase.from("enquiries").select("id",{count:"exact",head:true}).gte("created_at",startToday.toISOString()):Promise.resolve(emptyCount),
    canEnquiries?supabase.from("enquiries").select("id",{count:"exact",head:true}):Promise.resolve(emptyCount),
    canProperties?supabase.from("properties").select("created_at").gte("created_at",startYear.toISOString()):Promise.resolve(emptyRows),
    canEnquiries?supabase.from("enquiries").select("created_at").gte("created_at",startYear.toISOString()):Promise.resolve(emptyRows),
    canAudit?supabase.from("audit_logs").select("id,action,entity_type,entity_reference,outcome,created_at").order("created_at",{ascending:false}).limit(8):Promise.resolve({data:[],error:null}),
  ]);
  const failures=[users,total,pending,published,drafts,rejected,todayEnquiries,totalEnquiries,listingsSeries,enquirySeries,activity].map((result)=>result.error).filter(Boolean);if(failures.length)logEvent("error","admin.dashboard_query_failed",{codes:[...new Set(failures.map((error)=>error?.code||"query_failed"))]});
  const cards=[["Total Users",users.count,canUsers],["Total Properties",total.count,canProperties],["Pending Approval",pending.count,canProperties],["Published",published.count,canProperties],["Draft",drafts.count,canProperties],["Rejected",rejected.count,canProperties],["Today's Enquiries",todayEnquiries.count,canEnquiries],["Total Enquiries",totalEnquiries.count,canEnquiries]].filter((item)=>item[2]);const months=Array.from({length:12},(_,index)=>{const date=new Date();date.setMonth(date.getMonth()-(11-index),1);return monthKey(date.toISOString())});const values=(rows:{created_at:string}[]|null)=>months.map((month)=>rows?.filter((row)=>monthKey(row.created_at)===month).length||0);const listingValues=values(listingsSeries.data),enquiryValues=values(enquirySeries.data),max=Math.max(1,...listingValues,...enquiryValues);const permissions=Array.isArray((context as {permissions?:unknown}).permissions)?(context as {permissions:string[]}).permissions:[];
  return <main id="main" className="portal-page admin-portal"><div className="shell"><div className="portal-title"><div><p className="eyebrow">Secure administration</p><h1>Operations overview</h1><p>Launch operations, queues and activity in one workspace.</p></div><div className="portal-actions"><Link className="button button-light" href="/dashboard">Owner dashboard</Link><form action="/api/auth/logout" method="post"><button className="text-button">Sign out</button></form></div></div><AdminNavigation permissions={permissions}/>{failures.length>0&&<div className="config-warning" role="alert"><h2>Some dashboard data could not be loaded</h2><p>Your session is valid, but an authorised database query failed. Retry this page; if it continues, check the server request ID and RBAC migration.</p><Link className="button button-small" href="/admin">Retry</Link></div>}{!hasPermission(context,PERMISSIONS.rolesManage)&&<p className="form-message" role="status">This is a limited administrator account. Only assigned modules are shown.</p>}<section className="metric-grid admin-metrics">{cards.map(([title,value])=><article key={String(title)}><strong>{value??0}</strong><h2>{title}</h2></article>)}</section><section className="admin-dashboard-grid">{canProperties&&<Chart title="Monthly listings" months={months} values={listingValues} max={max}/>} {canEnquiries&&<Chart title="Monthly enquiries" months={months} values={enquiryValues} max={max}/>}</section><section className="admin-dashboard-grid">{canAudit&&<article className="portal-section"><h2>Recent activity</h2>{activity.data?.length?<ol className="activity-list">{activity.data.map((item)=><li key={item.id}><strong>{item.action}</strong><span>{item.entity_reference||item.entity_type} · {new Date(item.created_at).toLocaleString("en-IN")}</span></li>)}</ol>:<p>No accessible activity records.</p>}</article>}<article className="portal-section"><h2>Quick actions</h2><div className="quick-actions">{canProperties&&<Link href="/admin/properties?status=pending_review">Review pending properties</Link>}{canEnquiries&&<Link href="/admin/enquiries?status=new">Assign new enquiries</Link>}{hasPermission(context,PERMISSIONS.settingsManage)&&<Link href="/admin/masters">Manage master data</Link>}{hasPermission(context,PERMISSIONS.analyticsRead)&&<Link href="/admin/reports">Export operational reports</Link>}</div></article></section></div></main>;
}
function Chart({title,months,values,max}:{title:string;months:string[];values:number[];max:number}){return <article className="portal-section"><h2>{title}</h2><div className="mini-chart" aria-label={`${title} chart`}>{months.map((month,index)=><div key={month}><span style={{height:`${Math.max(4,(values[index]/max)*100)}%`}}/><small>{month.slice(5)}</small></div>)}</div></article>}
function AdminFailure(){return <main id="main" className="portal-page"><div className="shell"><div className="config-warning" role="alert"><h1>Administration permissions could not be loaded</h1><p>Your login session is valid, but role information is unavailable. Apply the authentication/RBAC hotfix migration and retry.</p><Link className="button" href="/admin">Retry</Link></div></div></main>}
