import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read=(path:string)=>readFile(new URL(path,import.meta.url),"utf8");
test("homepage includes every approved public module",async()=>{const [home,slider,header]=await Promise.all([read("../app/page.tsx"),read("../src/components/hero-slider.tsx"),read("../src/components/public-navigation.tsx")]);for(const marker of ["HeroSlider","Why choose OngoleProperty","Featured and latest properties","Real Estate Agent","Paying guest","Advertisement","Post Property"])assert.match(home,new RegExp(marker,"i"));assert.doesNotMatch(home,/Customer experiences|testimonial/i);assert.match(slider,/setInterval/);assert.match(slider,/ArrowLeft/);assert.match(header,/menu-open/);assert.match(header,/Escape/)});
test("listing supports views, complete URL filters, sorting and pagination",async()=>{const [page,filters,results]=await Promise.all([read("../app/properties/page.tsx"),read("../src/components/property-filter-form.tsx"),read("../src/components/listing-results.tsx")]);assert.match(page,/listPublicProperties/);for(const field of ["bedrooms","bathrooms","facing","furnishing","amenities","minArea","maxArea"])assert.match(filters,new RegExp(`name=\\"${field}\\"`));assert.match(results,/sessionStorage/);assert.match(results,/property-list/);assert.match(results,/view=\{view\}/)});
test("details hide optional sections and protect public database columns",async()=>{const [page,migration,enquiry]=await Promise.all([read("../app/property/[slug]/page.tsx"),read("../supabase/migrations/202607170002_public_column_security.sql"),read("../app/api/enquiries/route.ts")]);assert.match(page,/property\.description\?/);assert.match(page,/property\.amenities\.length>0&&/);assert.match(page,/videoId&&/);assert.match(page,/getPublicPropertyMap/);assert.match(migration,/revoke select on public\.properties from anon/i);assert.doesNotMatch(migration,/grant select \([^)]*owner_id/i);assert.doesNotMatch(migration,/grant select \([^)]*latitude/i);assert.match(enquiry,/parsed\.data\.website/)});
test("SEO includes metadata, structured data, robots and graceful sitemap fallback",async()=>{const [layout,details,robots,sitemap]=await Promise.all([read("../app/layout.tsx"),read("../app/property/[slug]/page.tsx"),read("../app/robots.ts"),read("../app/sitemap.ts")]);assert.match(layout,/Organization/);assert.match(layout,/WebSite/);assert.match(details,/BreadcrumbList/);assert.match(details,/RealEstateListing/);assert.match(robots,/sitemap/);assert.match(sitemap,/try\{/);assert.match(sitemap,/catch\{/)});
