import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import test from "node:test";import {emailTemplate} from "../src/lib/email/templates";import {checkRateLimit} from "../src/lib/security/rate-limit";
const read=(path:string)=>readFile(new URL(path,import.meta.url),"utf8");
test("Sprint 2 migration provides owner, CRM, master and audit foundations",async()=>{const sql=await read("../supabase/migrations/202607170004_sprint2_operations.sql");for(const marker of ["master_items","enquiry_notes","owner_soft_delete_property","duplicate_owner_property","record_audit_event","audit_user_role_change","refresh_master_usage_counts"])assert.match(sql,new RegExp(marker));assert.match(sql,/properties\.manage/);assert.doesNotMatch(sql,/properties\.update/)});
test("owner dashboard includes lifecycle, editing and media controls",async()=>{const [dashboard,manage,propertyApi,mediaApi]=await Promise.all([read("../app/dashboard/page.tsx"),read("../app/dashboard/properties/[id]/page.tsx"),read("../app/api/properties/[id]/route.ts"),read("../app/api/properties/[id]/media/[mediaId]/route.ts")]);for(const status of ["draft","pending_review","approved","rejected","archived"])assert.match(dashboard,new RegExp(status));for(const marker of ["Preview","Duplicate property","Approval history","youtubeUrl","Make cover"])assert.match(manage,new RegExp(marker,"i"));assert.match(propertyApi,/owner_soft_delete_property/);assert.match(mediaApi,/storage_path/)});
test("admin operations expose metrics, CRM, masters, reports and audit",async()=>{const files=await Promise.all([read("../app/admin/page.tsx"),read("../app/admin/enquiries/page.tsx"),read("../app/admin/masters/page.tsx"),read("../app/admin/reports/page.tsx"),read("../app/admin/audit/page.tsx")]);for(const marker of ["Total Users","Monthly listings","Today's Enquiries"])assert.match(files[0],new RegExp(marker));assert.match(files[1],/Enquiry CRM/);assert.match(files[2],/usage_count/);assert.match(files[3],/Excel/);assert.match(files[4],/Audit logs/)});
test("email templates escape untrusted content",()=>{const result=emailTemplate("property-rejected",{name:"<script>alert(1)</script>",reference:"PROP-1",reason:"<b>unsafe</b>"});assert.doesNotMatch(result.html,/<script>/);assert.doesNotMatch(result.html,/<b>unsafe/);assert.match(result.html,/&lt;script&gt;/)});
test("in-memory rate limiter remains available without Redis",async()=>{const key=`test-${Date.now()}-${Math.random()}`;assert.equal((await checkRateLimit(key,2,60_000)).allowed,true);assert.equal((await checkRateLimit(key,2,60_000)).allowed,true);assert.equal((await checkRateLimit(key,2,60_000)).allowed,false)});
test("Turnstile covers authentication and property submission with graceful widgets",async()=>{const [auth,login,register,registrationForm,submit,post]=await Promise.all([read("../app/api/auth/[action]/route.ts"),read("../app/login/page.tsx"),read("../app/register/page.tsx"),read("../src/components/registration-form.tsx"),read("../app/api/properties/[id]/submit/route.ts"),read("../app/post-property/page.tsx")]);assert.match(auth,/verifyCaptcha/);assert.match(login,/CaptchaWidget/);assert.match(register,/RegistrationForm/);assert.match(registrationForm,/CaptchaWidget/);assert.match(submit,/verifyCaptcha/);assert.match(post,/CaptchaWidget/)});
test("reports guard spreadsheet formulas and provide CSV and XLSX",async()=>{const report=await read("../app/api/admin/reports/[entity]/route.ts");assert.match(report,/\^\[=\+\\-@/);assert.match(report,/text\/csv/);assert.match(report,/spreadsheetml/);assert.match(report,/record_audit_event/)});
