import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminNavigation } from "@/src/components/admin-navigation";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";

export const dynamic="force-dynamic";export const metadata:Metadata={title:"Master data",robots:{index:false,follow:false}};
const kinds=["property_category","property_type","location","amenity","highlight","tag","facing","ownership","district","city","locality","advertisement_type"] as const;
type MasterRow={id:string;name:string;sort_order?:number;is_active:boolean;usage_count?:number;category_id?:string};

export default async function MastersPage({searchParams}:{searchParams:Promise<{kind?:string;q?:string}>}){
  const supabase=await createSupabaseServerClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/login?returnTo=/admin/masters");const {data:allowed}=await supabase.rpc("has_permission",{required_permission:"settings.manage"});if(!allowed)redirect("/admin");
  const params=await searchParams;const kind=kinds.includes(params.kind as typeof kinds[number])?params.kind as typeof kinds[number]:"property_category";const table=kind==="property_category"?"property_categories":kind==="property_type"?"property_types":kind==="location"?"locations":"master_items";
  let query=supabase.from(table).select("*").is("deleted_at",null).order("sort_order").order("name");if(table==="master_items")query=query.eq("kind",kind);if(params.q)query=query.ilike("name",`%${params.q.replace(/[%(),]/g,"")}%`);
  const [{data},{data:categories}]=await Promise.all([query,supabase.from("property_categories").select("id,name").eq("is_active",true).is("deleted_at",null).order("name")]);const items=(data||[]) as unknown as MasterRow[];
  return <main id="main" className="portal-page admin-portal"><div className="shell"><div className="portal-title"><div><p className="eyebrow">Dynamic configuration</p><h1>Master data</h1><p>Add, order, activate or retire operational values without code changes.</p></div></div><AdminNavigation/><nav className="master-tabs">{kinds.map((item)=><Link key={item} className={kind===item?"is-active":""} href={`/admin/masters?kind=${item}`}>{item.replaceAll("_"," ")}</Link>)}</nav><section className="admin-dashboard-grid master-layout"><article className="portal-section"><h2>Add {kind.replaceAll("_"," ")}</h2><form className="stack-form" action="/api/admin/masters" method="post"><input type="hidden" name="action" value="create"/><input type="hidden" name="kind" value={kind}/><label>Name<input required name="name" minLength={2}/></label>{kind==="property_type"&&<label>Category<select required name="parentId"><option value="">Choose category</option>{categories?.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>Display order<input name="sortOrder" type="number" min="0" defaultValue="0"/></label><button className="button">Add record</button></form></article><article className="portal-section"><form className="admin-filters"><input type="hidden" name="kind" value={kind}/><input name="q" defaultValue={params.q} placeholder="Search master data"/><button className="button button-small">Search</button></form><div className="master-list">{items.map((item)=><article key={item.id}><form action="/api/admin/masters" method="post"><input type="hidden" name="action" value="update"/><input type="hidden" name="kind" value={kind}/><input type="hidden" name="id" value={item.id}/><input name="name" defaultValue={item.name}/><input aria-label="Display order" name="sortOrder" type="number" min="0" defaultValue={item.sort_order||0}/>{kind==="property_type"&&<input type="hidden" name="parentId" value={item.category_id}/>}<button>Save</button></form><div><span className={`status ${item.is_active?"status-published":"status-archived"}`}>{item.is_active?"active":"inactive"}</span><span>Usage {item.usage_count||0}</span><form action="/api/admin/masters" method="post"><input type="hidden" name="kind" value={kind}/><input type="hidden" name="id" value={item.id}/><button name="action" value={item.is_active?"deactivate":"activate"}>{item.is_active?"Deactivate":"Activate"}</button><button className="danger-link" name="action" value="delete">Delete</button></form></div></article>)}{!items.length&&<div className="empty-state compact"><h3>No master records</h3></div>}</div></article></section></div></main>;
}
