import type {Metadata} from "next";
import Link from "next/link";
import {redirect} from "next/navigation";
import {CreditCard,FileText,Receipt,ShieldCheck} from "lucide-react";
import {PaymentButton} from "@/src/components/billing/payment-button";
import {DashboardShell,DataTable,EmptyState,PlanUsageCard,StatCard,StatusBadge} from "@/src/components/dashboard/dashboard-shell";
import {createSupabaseServerClient} from "@/src/lib/supabase/server";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Billing and plan",robots:{index:false,follow:false}};
export default async function BillingPage({searchParams}:{searchParams:Promise<{plan?:string;notice?:string}>}){
  const params=await searchParams;const supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/login?returnTo=/dashboard/billing");
  const[{data:context},{data:plans},{data:payments},{data:invoices},{data:manual}]=await Promise.all([supabase.rpc("get_my_plan_context"),supabase.from("plans").select("*").eq("is_active",true).eq("is_public",true).order("display_order"),supabase.from("payments").select("id,amount_inr,currency,provider,status,payment_method,created_at,plan_id").eq("user_id",auth.user.id).order("created_at",{ascending:false}).limit(20),supabase.from("invoices").select("id,invoice_number,total,currency,status,issued_at").eq("user_id",auth.user.id).order("issued_at",{ascending:false}).limit(20),supabase.from("manual_payment_requests").select("id,amount,status,transaction_reference,created_at").eq("user_id",auth.user.id).order("created_at",{ascending:false}).limit(10)]);
  const value=context as {plan?:{id:string;name:string;listing_limit:number;pg_listing_limit:number;featured_listing_allowance:number};subscription?:{id?:string;status?:string;ends_at?:string;cancelled_at?:string};usage?:{properties:number;pg_listings:number}}|null;const selected=plans?.find((plan)=>plan.id===params.plan);
  return <DashboardShell title="Billing & Plan" description="Manage your subscription, usage, payments and invoices." actions={<Link className="button button-light" href="/pricing">Compare plans</Link>} breadcrumbs={[{label:"Dashboard",href:"/dashboard"},{label:"Billing"}]}>
    {params.notice==="manual-submitted"&&<p className="form-message success">Manual payment submitted for finance review.</p>}{params.notice==="cancelled"&&<p className="form-message success">Renewal was cancelled. Existing access remains available until the recorded end date.</p>}
    <section className="dashboard-stat-grid"><StatCard label="Active plan" value={value?.plan?.name||"Free"} icon={<ShieldCheck/>}/><StatCard label="Subscription status" value={value?.subscription?.status||"fallback"} icon={<CreditCard/>}/><StatCard label="Payments" value={payments?.length||0} icon={<Receipt/>}/><StatCard label="Invoices" value={invoices?.length||0} icon={<FileText/>}/></section>
    <section className="dashboard-grid-2"><PlanUsageCard plan={value?.plan?.name||"Free"} used={value?.usage?.properties||0} limit={value?.plan?.listing_limit||1} label="Property listings"/><PlanUsageCard plan={value?.plan?.name||"Free"} used={value?.usage?.pg_listings||0} limit={value?.plan?.pg_listing_limit||0} label="PG listings"/></section>
    {value?.subscription?.id&&["trialing","active","past_due","paused"].includes(value.subscription.status||"")&&<section className="dashboard-card dashboard-section"><header><div><h2>Cancellation status</h2><p>Current access ends {value.subscription.ends_at?new Date(value.subscription.ends_at).toLocaleDateString("en-IN"):"at the subscription end date"}. Listings are not deleted.</p></div></header><form action="/api/billing/subscription" method="post"><input type="hidden" name="subscriptionId" value={value.subscription.id}/><button className="danger-button" name="action" value="cancel">Cancel renewal</button></form></section>}
    {selected&&selected.price>0&&<section className="dashboard-card dashboard-section"><header><div><h2>Upgrade to {selected.name}</h2><p>{selected.description}</p></div><strong>₹{Number(selected.price).toLocaleString("en-IN")}</strong></header><div className="dashboard-title-actions"><PaymentButton planId={selected.id}/><Link className="button button-light" href={`/dashboard/billing/manual?plan=${selected.id}`}>Pay manually</Link></div><p className="form-note">Online activation occurs only after a signed provider webhook confirms capture.</p></section>}
    <section className="dashboard-section"><div className="dashboard-section-head"><h2>Available plans</h2></div><div className="billing-plan-grid">{plans?.map((plan)=><article className="dashboard-card" key={plan.id}><h3>{plan.name}</h3><strong>{plan.price?`₹${Number(plan.price).toLocaleString("en-IN")}`:"Free"}</strong><p>{plan.listing_limit} properties · {plan.pg_listing_limit} PGs · {plan.image_limit_per_listing} images</p>{plan.id!==value?.plan?.id&&plan.price>0&&<Link className="button button-small" href={`/dashboard/billing?plan=${plan.id}`}>Select</Link>}</article>)}</div></section>
    <section className="dashboard-grid-2"><article className="dashboard-card"><header><h2>Payment history</h2></header>{payments?.length?<DataTable caption="Payments" headers={["Date","Provider","Method","Amount","Status"]}>{payments.map((payment)=><tr key={payment.id}><td>{new Date(payment.created_at).toLocaleDateString("en-IN")}</td><td>{payment.provider}</td><td>{payment.payment_method||"—"}</td><td>₹{Number(payment.amount_inr).toLocaleString("en-IN")}</td><td><StatusBadge status={payment.status}/></td></tr>)}</DataTable>:<EmptyState title="No payments" description="Completed and failed payment attempts appear here."/>}</article><article className="dashboard-card"><header><h2>Invoices</h2></header>{invoices?.length?<DataTable caption="Invoices" headers={["Invoice","Issued","Amount","Status"]}>{invoices.map((invoice)=><tr key={invoice.id}><td>{invoice.invoice_number}</td><td>{new Date(invoice.issued_at).toLocaleDateString("en-IN")}</td><td>₹{Number(invoice.total).toLocaleString("en-IN")}</td><td><StatusBadge status={invoice.status}/></td></tr>)}</DataTable>:<EmptyState title="No invoices" description="Invoices are generated after captured payments."/>}</article></section>
    <section className="dashboard-card dashboard-section"><header><h2>Manual payment requests</h2><Link href="/dashboard/billing/manual">Submit payment</Link></header>{manual?.length?<DataTable caption="Manual payments" headers={["Reference","Date","Amount","Status"]}>{manual.map((item)=><tr key={item.id}><td>{item.transaction_reference}</td><td>{new Date(item.created_at).toLocaleDateString("en-IN")}</td><td>₹{Number(item.amount).toLocaleString("en-IN")}</td><td><StatusBadge status={item.status}/></td></tr>)}</DataTable>:<EmptyState title="No manual requests" description="Use manual payment when online checkout is unavailable."/>}</section>
  </DashboardShell>
}
