import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminNavigation } from "@/src/components/admin-navigation";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Property administration",robots:{index:false,follow:false}};
const statuses=["draft","pending_review","changes_requested","approved","published","rejected","archived","sold","rented","leased"];
const bulkActions=[["publish","Publish approved"],["archive","Archive"],["activate","Activate archived"],["deactivate","Deactivate"],["delete","Soft delete"],["feature","Feature"],["unfeature","Remove feature"],["verify","Verify"],["unverify","Remove verification"],["pin","Pin"],["unpin","Unpin"]] as const;

export default async function AdminPropertiesPage({searchParams}:{searchParams:Promise<{status?:string;q?:string;page?:string}>}){
  const supabase=await createSupabaseServerClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/login?returnTo=/admin/properties");const {data:allowed}=await supabase.rpc("has_permission",{required_permission:"properties.read"});if(!allowed)redirect("/dashboard");
  const params=await searchParams;const page=Math.max(1,Number(params.page)||1),pageSize=20;let query=supabase.from("properties").select("id,reference_no,title,status,locality_text,city_text,price_inr,submitted_at,updated_at,is_featured,is_verified,is_pinned,deleted_at",{count:"exact"}).order("updated_at",{ascending:false}).range((page-1)*pageSize,page*pageSize-1);if(statuses.includes(params.status||""))query=query.eq("status",params.status);if(params.q)query=query.or(`title.ilike.%${params.q.replace(/[%(),]/g,"")}%,reference_no.ilike.%${params.q.replace(/[%(),]/g,"")}%`);const {data:properties,count}=await query;const pages=Math.max(1,Math.ceil((count||0)/pageSize));
  return <main id="main" className="portal-page admin-portal"><div className="shell"><div className="portal-title"><div><p className="eyebrow">Property operations</p><h1>All properties</h1><p>Search, review and apply controlled bulk actions.</p></div></div><AdminNavigation/><form className="admin-filters"><input name="q" defaultValue={params.q} placeholder="Title or reference"/><select name="status" defaultValue={params.status||""}><option value="">All statuses</option>{statuses.map((status)=><option key={status}>{status}</option>)}</select><button className="button button-small">Search</button></form><form action="/api/admin/properties/bulk" method="post"><div className="bulk-toolbar"><select required name="action" defaultValue=""><option value="" disabled>Bulk action</option>{bulkActions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="button button-small">Apply</button><Link className="button button-light button-small" href="/api/admin/reports/properties?format=csv">Export CSV</Link></div><section className="portal-section admin-table-wrap">{properties?.length?<div className="admin-table property-admin-table"><div className="admin-row admin-head"><span>Select</span><span>Property</span><span>Location</span><span>Status</span><span>Flags</span><span/></div>{properties.map((property)=><div className="admin-row" key={property.id}><span><input type="checkbox" name="ids" value={property.id} aria-label={`Select ${property.reference_no}`}/></span><span><strong>{property.title}</strong><small>{property.reference_no}</small></span><span>{property.locality_text}, {property.city_text}</span><span><i className={`status status-${property.status}`}>{property.status.replaceAll("_"," ")}</i></span><span className="flag-list">{property.is_verified&&<b>Verified</b>}{property.is_featured&&<b>Featured</b>}{property.is_pinned&&<b>Pinned</b>}{property.deleted_at&&<b>Deleted</b>}</span><span><Link href={`/admin/properties/${property.id}`}>Manage →</Link></span></div>)}</div>:<div className="empty-state"><h2>No matching properties</h2></div>}</section></form><nav className="pagination">{page>1&&<Link href={`/admin/properties?page=${page-1}`}>Previous</Link>}<span>Page {page} of {pages}</span>{page<pages&&<Link href={`/admin/properties?page=${page+1}`}>Next</Link>}</nav></div></main>;
}
