import type { Metadata } from "next";
import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { AdminNavigation } from "@/src/components/admin-navigation";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";

export const dynamic="force-dynamic";export const metadata:Metadata={title:"CRM enquiry",robots:{index:false,follow:false}};
const statuses=["new","assigned","contacted","follow_up","qualified","closed","lost","spam"];
function one<T>(value:T|T[]|null):T|undefined{return Array.isArray(value)?value[0]:value||undefined}

export default async function EnquiryPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const supabase=await createSupabaseServerClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user)redirect(`/login?returnTo=/admin/enquiries/${id}`);const {data:allowed}=await supabase.rpc("has_permission",{required_permission:"enquiries.read"});if(!allowed)redirect("/admin");
  const [{data:e},{data:notes},{data:assignees}]=await Promise.all([supabase.from("enquiries").select("*,properties(id,title,reference_no,owner_id,profiles!properties_owner_id_fkey(full_name,reference_no))").eq("id",id).maybeSingle(),supabase.from("enquiry_notes").select("id,note,created_at,profiles!enquiry_notes_author_id_fkey(full_name)").eq("enquiry_id",id).order("created_at",{ascending:false}),supabase.from("profiles").select("id,full_name,reference_no").eq("status","active").order("full_name").limit(200)]);if(!e)notFound();const property=one(e.properties);const owner=property?one(property.profiles):undefined;
  return <main id="main" className="portal-page admin-portal"><div className="shell"><div className="portal-title"><div><p className="eyebrow">{e.reference_no}</p><h1>{e.name}</h1><p>{e.mobile} · {e.email||"No email"} · Created {new Date(e.created_at).toLocaleString("en-IN")}</p></div><Link className="button button-light" href="/admin/enquiries">Back to CRM</Link></div><AdminNavigation/><div className="review-layout"><section className="portal-section"><h2>Lead context</h2><dl className="review-facts"><div><dt>Property</dt><dd>{property?.title||"General enquiry"} {property?.reference_no&&`(${property.reference_no})`}</dd></div><div><dt>Owner</dt><dd>{owner?.full_name||"—"} {owner?.reference_no}</dd></div><div><dt>User</dt><dd>{e.user_id||"Guest visitor"}</dd></div><div><dt>Visitor</dt><dd>{e.visitor_reference||e.source}</dd></div><div className="wide"><dt>Message</dt><dd>{e.message}</dd></div></dl><h2>Notes &amp; timeline</h2><form className="stack-form" action={`/api/admin/enquiries/${id}`} method="post"><input type="hidden" name="action" value="note"/><label>Internal note<textarea required name="note" minLength={1} maxLength={4000} rows={4}/></label><button className="button button-small">Add note</button></form><ol className="timeline">{notes?.map((note)=>{const author=one(note.profiles);return <li key={note.id}><strong>{author?.full_name||"Administrator"}</strong><span>{new Date(note.created_at).toLocaleString("en-IN")}</span><p>{note.note}</p></li>})}<li><strong>Enquiry received</strong><span>{new Date(e.created_at).toLocaleString("en-IN")}</span></li></ol></section><aside className="review-actions"><h2>Update lead</h2><form className="stack-form" action={`/api/admin/enquiries/${id}`} method="post"><input type="hidden" name="action" value="update"/><label>Status<select name="status" defaultValue={e.status}>{statuses.map((status)=><option key={status}>{status}</option>)}</select></label><label>Priority<select name="priority" defaultValue={e.priority}>{["low","normal","high","urgent"].map((priority)=><option key={priority}>{priority}</option>)}</select></label><label>Assigned to<select name="assignedTo" defaultValue={e.assigned_to||""}><option value="">Unassigned</option>{assignees?.map((person)=><option key={person.id} value={person.id}>{person.full_name} · {person.reference_no}</option>)}</select></label><label>Follow-up date<input type="datetime-local" name="followUpAt" defaultValue={e.follow_up_at?new Date(e.follow_up_at).toISOString().slice(0,16):""}/></label><button className="button">Save CRM update</button></form></aside></div></div></main>;
}
