import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AdSlot } from "@/src/components/ad-slot";
import { EnquiryForm } from "@/src/components/enquiry-form";
import { PropertyActions } from "@/src/components/property-actions";
import { PropertyCard } from "@/src/components/property-card";
import { PropertyGallery } from "@/src/components/property-gallery";
import { siteConfig } from "@/src/config/site";
import { env } from "@/src/lib/env";
import { areaEquivalents, formatArea } from "@/src/lib/area-conversion";
import { formatPrice, propertyPurposeLabel } from "@/src/lib/format";
import { getPublicProperty, getPublicPropertyContact, getPublicPropertyMap, getPublicPropertySlugs, getSimilarProperties } from "@/src/lib/properties/public";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";
import { youtubeVideoId } from "@/src/lib/youtube";

export const revalidate=300;
export async function generateStaticParams(){return (await getPublicPropertySlugs(100)).map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const property=await getPublicProperty(slug);if(!property)return{};const description=`${property.propertyType} for ${propertyPurposeLabel(property).toLowerCase()} in ${property.locality}, ${property.city}. ${formatArea(property.areaValue,property.areaUnit)}. ${formatPrice(property.price,property.transactionType)}.`;return{title:`${property.title} in ${property.locality}`,description,alternates:{canonical:`/property/${property.slug}`},robots:{index:!property.isDemo,follow:!property.isDemo},openGraph:{title:property.title,description,url:`/property/${property.slug}`,type:"article"},twitter:{card:"summary_large_image",title:property.title,description}}}

export default async function PropertyPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const property=await getPublicProperty(slug);if(!property)notFound();const [similar,contact,mapPoint]=await Promise.all([getSimilarProperties(property),getPublicPropertyContact(property),getPublicPropertyMap(property)]);let authenticated=false;if(env.isSupabaseConfigured){try{const supabase=await createSupabaseServerClient();const {data}=await supabase.auth.getUser();authenticated=Boolean(data.user)}catch{authenticated=false}}
  const breadcrumbItems=[{name:"Home",url:"/"},{name:`Properties for ${propertyPurposeLabel(property)}`,url:`/properties?purpose=${property.transactionType}`},{name:property.category,url:`/properties?purpose=${property.transactionType}&category=${property.categorySlug}`},{name:property.propertyType,url:`/properties?purpose=${property.transactionType}&category=${property.categorySlug}&type=${property.propertyTypeSlug}`},{name:property.city,url:`/properties?location=${encodeURIComponent(property.city)}`},{name:property.title,url:`/property/${property.slug}`}];
  const propertySchema={"@context":"https://schema.org","@type":"RealEstateListing",name:property.title,url:`${siteConfig.url}/property/${property.slug}`,description:property.description,identifier:property.reference,datePosted:property.publishedAt,address:{"@type":"PostalAddress",addressLocality:property.locality,addressRegion:property.state,addressCountry:"IN"},offers:{"@type":"Offer",price:property.price,priceCurrency:"INR",availability:"https://schema.org/InStock"}};
  const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:breadcrumbItems.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,item:`${siteConfig.url}${item.url}`}))};const videoId=youtubeVideoId(property.videoUrl);const equivalents=areaEquivalents(property.areaValue,property.areaUnit).filter((item)=>["sq_ft","sq_yd","sq_m","acre","cent"].includes(item.unit)).slice(0,4);const publicPhone=contact?.phone||siteConfig.phone.replace(/\D/g,"");const publicPhoneHref=`tel:+91${publicPhone.slice(-10)}`;
  return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([propertySchema,breadcrumbSchema]).replace(/</g,"\\u003c")}}/><section className="detail-head shell"><nav className="breadcrumbs" aria-label="Breadcrumb">{breadcrumbItems.map((item,index)=><span key={item.name}>{index>0&&<b aria-hidden="true">›</b>}{index===breadcrumbItems.length-1?<span aria-current="page">{item.name}</span>:<Link href={item.url}>{item.name}</Link>}</span>)}</nav><div className="detail-title"><div><div className="badge-row static">{property.isVerified&&<span className="badge">Verified</span>}{property.isFeatured&&<span className="badge badge-warm">Featured</span>}{property.isDemo&&<span className="badge badge-neutral">Demo preview</span>}</div><p className="property-meta">{property.reference} · {property.category} · {property.propertyType}</p><h1>{property.title}</h1><p>{property.locality}, {property.city}, {property.district}</p></div><div className="detail-price"><strong>{formatPrice(property.price,property.transactionType)}</strong><span>{formatArea(property.areaValue,property.areaUnit)}</span></div></div><PropertyActions title={property.title} authenticated={authenticated} returnPath={`/property/${property.slug}`} url={`${siteConfig.url}/property/${property.slug}`}/></section>
  <section className="shell detail-grid"><div className="detail-main"><PropertyGallery media={property.media} title={property.title}/><section className="detail-section"><h2>Property overview</h2><dl className="fact-grid"><div><dt>Purpose</dt><dd>{propertyPurposeLabel(property)}</dd></div><div><dt>Property type</dt><dd>{property.propertyType}</dd></div><div><dt>Area</dt><dd>{formatArea(property.areaValue,property.areaUnit)}</dd></div>{property.bedrooms&&<div><dt>Bedrooms</dt><dd>{property.bedrooms}</dd></div>}{property.bathrooms&&<div><dt>Bathrooms</dt><dd>{property.bathrooms}</dd></div>}{property.facing&&<div><dt>Facing</dt><dd>{property.facing}</dd></div>}{property.furnishing&&<div><dt>Furnishing</dt><dd>{property.furnishing}</dd></div>}</dl></section>
  {property.description&&<section className="detail-section"><h2>Property description</h2><p>{property.description}</p></section>}{property.highlights.length>0&&<section className="detail-section"><h2>Property highlights</h2><ul className="highlight-list">{property.highlights.map((item)=><li key={item}>{item}</li>)}</ul></section>}{property.amenities.length>0&&<section className="detail-section"><h2>Property amenities</h2><ul className="amenity-list">{property.amenities.map((item)=><li key={item}>{item}</li>)}</ul></section>}{property.tags.length>0&&<section className="detail-section"><h2>Property tags</h2><div className="tag-list">{property.tags.map((item)=><span key={item}>{item}</span>)}</div></section>}
  <section className="detail-section"><h2>Area conversion</h2><p>The stored area is {formatArea(property.areaValue,property.areaUnit)}. Useful equivalents are calculated consistently:</p><dl className="conversion-grid">{equivalents.map((item)=><div key={item.unit}><dt>{formatArea(item.value,item.unit)}</dt><dd>Equivalent</dd></div>)}</dl></section>
  {videoId&&<section className="detail-section"><h2>Property video</h2><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={`${property.title} video`} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen loading="lazy"/></div><a className="arrow-link" href={`https://youtu.be/${videoId}`} target="_blank" rel="noreferrer">Open video on YouTube →</a></section>}
  <section className="detail-section"><h2>Property location</h2><p>{property.locality}, {property.city}, {property.district}, {property.state}</p>{mapPoint&&process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY?<div className="map-frame"><iframe title={`Map for ${property.title}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://www.google.com/maps/embed/v1/place?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&q=${mapPoint.latitude},${mapPoint.longitude}`}/></div>:<p className="visibility-note">{property.isPremium?"Exact map access is unavailable until the permitted coordinates and Google Maps configuration are available.":"For privacy, free listings show locality and administrative area only; the exact map is not public."}</p>}</section>
  {similar.length>0&&<section className="detail-section similar-section"><h2>Similar properties</h2><div className="property-grid">{similar.map((item)=><PropertyCard key={item.id} property={item}/>)}</div></section>}</div>
  <aside className="enquiry-card"><p className="eyebrow">Interested in this property?</p><h2>Request details or a visit</h2><p>Your enquiry goes through OngoleProperty.com. Private owner details remain protected unless an approved visibility rule permits them.</p><EnquiryForm propertyReference={property.reference} propertyTitle={property.title} captchaSiteKey={process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY}/><div className="contact-options"><a href={publicPhoneHref}>Call {contact?.label||"OngoleProperty"}</a><a href={siteConfig.whatsappHref} target="_blank" rel="noreferrer">WhatsApp our team</a></div><AdSlot title="Sidebar advertisement" placeholder className="ad-sidebar"/></aside></section><div className="mobile-contact-bar"><a href={publicPhoneHref}>Call</a><a href={siteConfig.whatsappHref}>WhatsApp</a><a href="#enquiry">Enquire</a></div></main>}
