import type {Metadata} from "next";
import Link from "next/link";
import {MapPin} from "lucide-react";
import {notFound,permanentRedirect,redirect} from "next/navigation";
import {AdSlot} from "@/src/components/ad-slot";
import {ClickToLoadMap} from "@/src/components/click-to-load-map";
import {EnquiryForm} from "@/src/components/enquiry-form";
import {PropertyActions} from "@/src/components/property-actions";
import {PropertyCard} from "@/src/components/property-card";
import {PropertyGallery} from "@/src/components/property-gallery";
import {siteConfig} from "@/src/config/site";
import {areaEquivalents,formatArea,formatLocalArea} from "@/src/lib/area-conversion";
import {getActiveAdvertisement} from "@/src/lib/advertisements/public";
import {formatPropertyPrice,propertyPurposeLabel} from "@/src/lib/format";
import {getPropertyRedirect,getPropertySeoOverride,getPublicProperty,getPublicPropertyContact,getPublicPropertyMap,getPublicPropertySlugs,getSimilarProperties} from "@/src/lib/properties/public";
import {youtubeVideoId} from "@/src/lib/youtube";

export const revalidate=300;
export const propertyMapEnvironmentVariable=process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
export async function generateStaticParams(){return(await getPublicPropertySlugs(100)).map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const property=await getPublicProperty(slug);if(!property)return{};const price=formatPropertyPrice(property),automaticDescription=`${property.propertyType} for ${propertyPurposeLabel(property).toLowerCase()} in ${property.locality}, ${property.city}. ${formatLocalArea(property.areaValue,property.areaUnit)}. ${price}.`;const override=await getPropertySeoOverride(property.id);const og=override?.open_graph&&typeof override.open_graph==="object"&&!Array.isArray(override.open_graph)?override.open_graph as Record<string,unknown>:{};const robots=override?.robots&&typeof override.robots==="object"&&!Array.isArray(override.robots)?override.robots as Record<string,unknown>:{};const title=override?.title||`${property.title} in ${property.locality} | ${price}`,description=override?.description||automaticDescription,image=String(og.image||property.media[0]?.url||"")||undefined;return{title,description,alternates:{canonical:override?.canonical_url||`/property/${property.slug}`},robots:{index:property.isDemo?false:robots.index!==false,follow:property.isDemo?false:robots.follow!==false},openGraph:{title:String(og.title||title),description:String(og.description||description),url:override?.canonical_url||`/property/${property.slug}`,type:"article",images:image?[{url:image,alt:property.title}]:undefined},twitter:{card:"summary_large_image",title,description,images:image?[image]:undefined}}}

type Fact={label:string;value:string|number};
const present=(value:unknown)=>value!==undefined&&value!==null&&value!=="";
const text=(value:unknown)=>present(value)?String(value).replaceAll("_"," "):"";

export default async function PropertyPage({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const property=await getPublicProperty(slug);if(!property){const moved=await getPropertyRedirect(slug);if(moved){if(moved.status===301||moved.status===308)permanentRedirect(moved.path);redirect(moved.path)}notFound()}
  const[similar,contact,mapPoint,sidebarAd]=await Promise.all([getSimilarProperties(property,4),getPublicPropertyContact(property),getPublicPropertyMap(property),getActiveAdvertisement("sidebar")]);
  const purpose=propertyPurposeLabel(property),listingBase=property.transactionType==="sale"?"/properties-for-sale":"/properties-for-rent",detailTitle=`${property.bedrooms?`${property.bedrooms}BHK `:""}${property.propertyType} for ${purpose}`;const breadcrumbs=[{name:"Home",url:"/"},{name:property.transactionType==="sale"?"Properties for Sale":"Properties for Rent / Lease",url:listingBase},{name:`${property.propertyType} in ${property.city}`,url:`${listingBase}?city=${encodeURIComponent(property.city)}&type=${property.propertyTypeSlug}`},{name:detailTitle,url:`/property/${property.slug}`}];
  const price=formatPropertyPrice(property),propertySchema={"@context":"https://schema.org","@type":"RealEstateListing",name:detailTitle,url:`${siteConfig.url}/property/${property.slug}`,description:property.description,identifier:property.reference,datePosted:property.publishedAt,image:property.media.map((item)=>item.url),address:{"@type":"PostalAddress",addressLocality:property.locality,addressRegion:property.state,addressCountry:"IN"},offers:{"@type":"Offer",price:property.price,priceCurrency:"INR",availability:"https://schema.org/InStock"}};const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:breadcrumbs.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,item:`${siteConfig.url}${item.url}`}))};
  const details=property.details||{},type=property.propertyTypeSlug,isAgricultural=["agricultural-land","farm-land"].includes(type),isPlot=["open-plot","commercial-open-plot"].includes(type),isUnit=["apartment-flat","office","shop","shopping-complex"].includes(type),isLand=isAgricultural||isPlot;
  const floor=details.floor,totalFloors=details.total_floors,floorValue=present(floor)?`${Number(floor)===0?"Ground Floor":text(floor)}${present(totalFloors)?` of ${text(totalFloors)}`:""}`:"";
  const quickFacts:Fact[]=(isAgricultural?[{label:"Land Area",value:formatLocalArea(property.areaValue,property.areaUnit)},{label:"Type of Crop",value:text(details.crop_type)}]:isPlot?[{label:"Plot Area",value:formatLocalArea(property.areaValue,property.areaUnit)},{label:"Facing",value:property.facing||""}]:[{label:isUnit?"Built-up Area":"Area",value:formatLocalArea(property.areaValue,property.areaUnit)},{label:"Bedrooms",value:property.bedrooms||""},{label:"Bathrooms",value:property.bathrooms||""},{label:"Facing",value:property.facing||""},{label:"Floor",value:floorValue}]).filter((item)=>present(item.value));
  const basicFacts:Fact[]=[{label:"Property Type",value:property.propertyType},{label:"Purpose",value:purpose},{label:"Property Age",value:text(details.property_age)},{label:"Floor",value:floorValue},{label:"Furnishing",value:property.furnishing||""},{label:"Ownership",value:property.ownership||""},{label:"Soil Type",value:text(details.soil_type)},{label:"Fencing",value:text(details.fencing)},{label:"Electricity Connection",value:text(details.electricity_connection)},{label:"Road Access",value:text(details.road_access)}].filter((item)=>present(item.value));
  const areaFacts:Fact[]=(isAgricultural?[{label:"Land Area",value:formatLocalArea(property.areaValue,property.areaUnit)}]:isUnit?[{label:"Built-up Area",value:formatLocalArea(property.areaValue,property.areaUnit)},{label:"Carpet Area",value:text(details.carpet_area)},{label:"UDS",value:text(details.uds)}]:[{label:"Site Area",value:formatLocalArea(property.areaValue,property.areaUnit)}]).filter((item)=>present(item.value));
  const facilityLabels:Record<string,string>={parking:"Parking",power_backup:"Power Backup",generator:"Generator",security:"Security",cctv:"CCTV",lift:"Lift",fire_safety:"Fire Safety",waste_management:"Waste Management",balcony:"Balcony",pooja_room:"Pooja Room",store_room:"Store Room",servant_room:"Servant Room",gas_pipeline:"Gas Pipeline"};const facilities=[...new Set([...property.amenities,...Object.entries(facilityLabels).filter(([key])=>details[key]===true).map(([,label])=>label)])];
  const nearbyObject=details.nearby_places&&typeof details.nearby_places==="object"&&!Array.isArray(details.nearby_places)?details.nearby_places as Record<string,unknown>:{};const nearby=Object.entries(nearbyObject).map(([key,value])=>{const item=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};return{name:key==="other"?text(item.name):key.replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase()),distance:Number(item.distance),unit:text(item.unit)||"Meters"}}).filter((item)=>Number.isFinite(item.distance)).sort((a,b)=>a.distance-b.distance);
  const videoId=youtubeVideoId(property.videoUrl),equivalents=areaEquivalents(property.areaValue,property.areaUnit).filter((item)=>["gadi","sq_ft","sq_yd","sq_m","acre","cent"].includes(item.unit)).slice(0,5),publicPhone=contact?.phone||siteConfig.phone.replace(/\D/g,""),publicPhoneHref=`tel:+91${publicPhone.slice(-10)}`,whatsappHref=contact?`https://wa.me/91${publicPhone.slice(-10)}?text=${encodeURIComponent(`I am interested in ${property.title} (${property.reference}).`)}`:siteConfig.whatsappHref;
  return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([propertySchema,breadcrumbSchema]).replace(/</g,"\\u003c")}}/><section className="detail-head shell"><nav className="breadcrumbs" aria-label="Breadcrumb">{breadcrumbs.map((item,index)=><span key={item.name}>{index>0&&<b aria-hidden="true">›</b>}{index===breadcrumbs.length-1?<span aria-current="page">{item.name}</span>:<Link href={item.url}>{item.name}</Link>}</span>)}</nav><Link className="arrow-link" href={listingBase}>← Back to results</Link><div className="detail-title"><div><div className="badge-row static">{!property.isDemo&&<span className="badge">Verified</span>}{property.isFeatured&&<span className="badge badge-warm">Featured</span>}{property.isDemo&&<span className="badge badge-neutral">Demo preview</span>}</div><p className="property-meta">Property ID: {property.reference}</p><h1>{detailTitle}</h1><p className="location"><MapPin size={17} aria-hidden="true"/>{property.locality}, {property.city}, {property.district} District</p></div><div className="detail-price"><strong>{price}</strong><span>{formatLocalArea(property.areaValue,property.areaUnit)}</span></div></div><PropertyActions title={detailTitle} url={`${siteConfig.url}/property/${property.slug}`}/><nav className="detail-section-nav" aria-label="Property information"><a href="#overview">Overview</a>{property.highlights.length>0&&<a href="#highlights">Highlights</a>}{facilities.length>0&&<a href="#amenities">{isLand?"Features":"Amenities"}</a>}<a href="#description">Description</a>{property.googleMapsUrl&&<a href="#location">Map</a>}<a href="#enquiry">Contact</a></nav></section>
  <section className="shell detail-grid"><div className="detail-main"><PropertyGallery media={property.media} title={detailTitle}/><section className="detail-section" id="overview"><h2>Quick facts</h2><dl className="fact-grid">{quickFacts.map((item)=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl><h3 className="eyebrow">Basic details</h3><dl className="fact-grid">{basicFacts.map((item)=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl><h3 className="eyebrow">Area details</h3><dl className="fact-grid">{areaFacts.map((item)=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></section>
  {property.highlights.length>0&&<section className="detail-section" id="highlights"><h2>Highlights</h2><ul className="highlight-list">{property.highlights.map((item)=><li key={item}>{item}</li>)}</ul></section>}{facilities.length>0&&<section className="detail-section" id="amenities"><h2>{isLand?"Property Features":"Amenities & Facilities"}</h2><ul className="amenity-list">{facilities.map((item)=><li key={item}>{item}</li>)}</ul></section>}<section className="detail-section" id="description"><h2>Description</h2>{property.description&&<p>{property.description}</p>}{property.tags.length>0&&<div className="tag-list">{property.tags.map((item)=><span key={item}>{item}</span>)}</div>}</section>
  <section className="detail-section"><h2>Area conversion</h2><p>The listed area is {formatLocalArea(property.areaValue,property.areaUnit)}.</p><dl className="conversion-grid">{equivalents.map((item)=><div key={item.unit}><dt>{formatArea(item.value,item.unit)}</dt><dd>Equivalent</dd></div>)}</dl></section>{videoId&&<section className="detail-section"><h2>Property video</h2><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={`${detailTitle} video`} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen loading="lazy"/></div><a className="arrow-link" href={`https://youtu.be/${videoId}`} target="_blank" rel="noreferrer">Open video on YouTube →</a></section>}
  {property.googleMapsUrl&&<section className="detail-section" id="location"><h2>Map and location</h2><p>{property.locality}, {property.city}, {property.district}, {property.state}</p>{mapPoint&&<ClickToLoadMap latitude={mapPoint.latitude} longitude={mapPoint.longitude} title={detailTitle}/>}<a className="arrow-link" href={property.googleMapsUrl} target="_blank" rel="noreferrer">View on Google Maps →</a></section>}{nearby.length>0&&<section className="detail-section"><h2>Nearby Places</h2><dl className="fact-grid">{nearby.map((item)=><div key={item.name}><dt>{item.name}</dt><dd>{item.distance.toLocaleString("en-IN")} {item.unit}</dd></div>)}</dl></section>}{similar.length>0&&<section className="detail-section similar-section"><h2>Similar Properties</h2><div className="property-grid">{similar.map((item)=><PropertyCard key={item.id} property={item}/>)}</div></section>}</div>
  <aside className="enquiry-card" id="enquiry"><p className="eyebrow">Interested in this property?</p><strong>{price}</strong><h2>{detailTitle}</h2><p>{property.locality}, {property.city}</p><EnquiryForm propertyReference={property.reference} propertyTitle={property.title} propertyId={property.id} captchaSiteKey={process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY}/><div className="contact-options"><a href={publicPhoneHref}>Call {contact?.label||"OngoleProperty"}</a><a href={whatsappHref} target="_blank" rel="noreferrer">WhatsApp {contact?.label||"our team"}</a></div>{sidebarAd&&<AdSlot title={sidebarAd.title} image={sidebarAd.image} alt={sidebarAd.alt} href={sidebarAd.href} className="ad-sidebar"/>}</aside></section><div className="mobile-contact-bar"><a href={publicPhoneHref}>Call Now</a><a href={whatsappHref}>WhatsApp</a></div></main>
}
