import type {Metadata} from "next";
import Link from "next/link";
import {notFound,permanentRedirect,redirect} from "next/navigation";
import {AdSlot} from "@/src/components/ad-slot";
import {EnquiryForm} from "@/src/components/enquiry-form";
import {PropertyActions} from "@/src/components/property-actions";
import {PropertyCard} from "@/src/components/property-card";
import {PropertyGallery} from "@/src/components/property-gallery";
import {ClickToLoadMap} from "@/src/components/click-to-load-map";
import {siteConfig} from "@/src/config/site";
import {areaEquivalents,formatArea,formatLocalArea} from "@/src/lib/area-conversion";
import {formatPrice,propertyPurposeLabel} from "@/src/lib/format";
import {getPropertyRedirect,getPropertySeoOverride,getPublicProperty,getPublicPropertyContact,getPublicPropertyMap,getPublicPropertySlugs,getSimilarProperties} from "@/src/lib/properties/public";
import {youtubeVideoId} from "@/src/lib/youtube";
import {getActiveAdvertisement} from "@/src/lib/advertisements/public";

export const revalidate=300;
export const propertyMapEnvironmentVariable=process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
export async function generateStaticParams(){return(await getPublicPropertySlugs(100)).map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const property=await getPublicProperty(slug);if(!property)return{};const automaticDescription=`${property.propertyType} for ${propertyPurposeLabel(property).toLowerCase()} in ${property.locality}, ${property.city}. ${formatLocalArea(property.areaValue,property.areaUnit)}. ${formatPrice(property.price,property.transactionType)}.`;const override=await getPropertySeoOverride(property.id);const og=override?.open_graph&&typeof override.open_graph==="object"&&!Array.isArray(override.open_graph)?override.open_graph as Record<string,unknown>:{};const robots=override?.robots&&typeof override.robots==="object"&&!Array.isArray(override.robots)?override.robots as Record<string,unknown>:{};const title=override?.title||`${property.title} in ${property.locality}`,description=override?.description||automaticDescription,image=String(og.image||property.media[0]?.url||"")||undefined;return{title,description,alternates:{canonical:override?.canonical_url||`/property/${property.slug}`},robots:{index:property.isDemo?false:robots.index!==false,follow:property.isDemo?false:robots.follow!==false},openGraph:{title:String(og.title||title),description:String(og.description||description),url:override?.canonical_url||`/property/${property.slug}`,type:"article",images:image?[{url:image,alt:property.title}]:undefined},twitter:{card:"summary_large_image",title,description,images:image?[image]:undefined}}}

export default async function PropertyPage({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const property=await getPublicProperty(slug);if(!property){const moved=await getPropertyRedirect(slug);if(moved){if(moved.status===301||moved.status===308)permanentRedirect(moved.path);redirect(moved.path)}notFound()}const[similar,contact,mapPoint,sidebarAd]=await Promise.all([getSimilarProperties(property),getPublicPropertyContact(property),getPublicPropertyMap(property),getActiveAdvertisement("sidebar")]);
  const listingBase=property.transactionType==="sale"?"/properties-for-sale":property.transactionType==="rent"?"/properties-for-rent":"/properties?purpose=lease";const breadcrumbs=[{name:"Home",url:"/"},{name:`Properties for ${propertyPurposeLabel(property)}`,url:listingBase},{name:property.category,url:`${listingBase}?category=${property.categorySlug}`},{name:property.propertyType,url:`${listingBase}?category=${property.categorySlug}&type=${property.propertyTypeSlug}`},{name:property.city,url:`${listingBase}?city=${encodeURIComponent(property.city)}`},{name:property.title,url:`/property/${property.slug}`}];
  const propertySchema={"@context":"https://schema.org","@type":"RealEstateListing",name:property.title,url:`${siteConfig.url}/property/${property.slug}`,description:property.description,identifier:property.reference,datePosted:property.publishedAt,image:property.media.map((item)=>item.url),address:{"@type":"PostalAddress",addressLocality:property.locality,addressRegion:property.state,addressCountry:"IN"},offers:{"@type":"Offer",price:property.price,priceCurrency:"INR",availability:"https://schema.org/InStock"}};const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:breadcrumbs.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,item:`${siteConfig.url}${item.url}`}))};
  const videoId=youtubeVideoId(property.videoUrl),equivalents=areaEquivalents(property.areaValue,property.areaUnit).filter((item)=>["gadi","sq_ft","sq_yd","sq_m","acre","cent"].includes(item.unit)).slice(0,5),publicPhone=contact?.phone||siteConfig.phone.replace(/\D/g,""),publicPhoneHref=`tel:+91${publicPhone.slice(-10)}`,whatsappHref=contact?`https://wa.me/91${publicPhone.slice(-10)}?text=${encodeURIComponent(`I am interested in ${property.title} (${property.reference}).`)}`:siteConfig.whatsappHref;
  return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([propertySchema,breadcrumbSchema]).replace(/</g,"\\u003c")}}/><section className="detail-head shell"><nav className="breadcrumbs" aria-label="Breadcrumb">{breadcrumbs.map((item,index)=><span key={item.name}>{index>0&&<b aria-hidden="true">›</b>}{index===breadcrumbs.length-1?<span aria-current="page">{item.name}</span>:<Link href={item.url}>{item.name}</Link>}</span>)}</nav><div className="detail-title"><div><div className="badge-row static">{property.isVerified&&<span className="badge">Verified</span>}{property.isFeatured&&<span className="badge badge-warm">Featured</span>}{property.isDemo&&<span className="badge badge-neutral">Demo preview</span>}</div><p className="property-meta">{property.reference} · {property.category} · {property.propertyType}</p><h1>{property.title}</h1><p>{property.locality}, {property.city}, {property.district}</p></div><div className="detail-price"><strong>{formatPrice(property.price,property.transactionType)}</strong><span>{formatLocalArea(property.areaValue,property.areaUnit)}</span></div></div><PropertyActions title={property.title} url={`${siteConfig.url}/property/${property.slug}`}/><nav className="detail-section-nav" aria-label="Property information"><a href="#overview">Overview</a>{property.highlights.length>0&&<a href="#highlights">Highlights</a>}{property.amenities.length>0&&<a href="#amenities">Amenities</a>}<a href="#description">Description</a><a href="#location">Map</a><a href="#enquiry">Contact</a></nav></section>
  <section className="shell detail-grid"><div className="detail-main"><PropertyGallery media={property.media} title={property.title}/><section className="detail-section" id="overview"><h2>Overview</h2><dl className="fact-grid"><div><dt>Purpose</dt><dd>{propertyPurposeLabel(property)}</dd></div><div><dt>Property type</dt><dd>{property.propertyType}</dd></div><div><dt>Area</dt><dd>{formatLocalArea(property.areaValue,property.areaUnit)}</dd></div>{property.bedrooms&&<div><dt>Bedrooms</dt><dd>{property.bedrooms}</dd></div>}{property.bathrooms&&<div><dt>Bathrooms</dt><dd>{property.bathrooms}</dd></div>}{property.facing&&<div><dt>Facing</dt><dd>{property.facing}</dd></div>}{property.furnishing&&<div><dt>Furnishing</dt><dd>{property.furnishing}</dd></div>}</dl></section>
  {property.highlights.length>0&&<section className="detail-section" id="highlights"><h2>Highlights</h2><ul className="highlight-list">{property.highlights.map((item)=><li key={item}>{item}</li>)}</ul></section>}{property.amenities.length>0&&<section className="detail-section" id="amenities"><h2>Amenities</h2><ul className="amenity-list">{property.amenities.map((item)=><li key={item}>{item}</li>)}</ul></section>}<section className="detail-section" id="description"><h2>Description</h2>{property.description?<p>{property.description}</p>:<p>Contact our team for the complete property description.</p>}{property.tags.length>0&&<div className="tag-list">{property.tags.map((item)=><span key={item}>{item}</span>)}</div>}</section>
  <section className="detail-section"><h2>Area conversion</h2><p>The listed area is {formatLocalArea(property.areaValue,property.areaUnit)}.</p><dl className="conversion-grid">{equivalents.map((item)=><div key={item.unit}><dt>{formatArea(item.value,item.unit)}</dt><dd>Equivalent</dd></div>)}</dl></section>{videoId&&<section className="detail-section"><h2>Property video</h2><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={`${property.title} video`} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen loading="lazy"/></div><a className="arrow-link" href={`https://youtu.be/${videoId}`} target="_blank" rel="noreferrer">Open video on YouTube →</a></section>}
  <section className="detail-section" id="location"><h2>Map and location</h2><p>{property.locality}, {property.city}, {property.district}, {property.state}</p>{mapPoint?<ClickToLoadMap latitude={mapPoint.latitude} longitude={mapPoint.longitude} title={property.title}/>:<p className="visibility-note">{property.isPremium?"Exact map access is unavailable until permitted coordinates are configured.":"For privacy, free listings show locality and administrative area only; the exact map is not public."}</p>}</section>{similar.length>0&&<section className="detail-section similar-section"><h2>Similar properties</h2><div className="property-grid">{similar.map((item)=><PropertyCard key={item.id} property={item}/>)}</div></section>}</div>
  <aside className="enquiry-card" id="enquiry"><p className="eyebrow">Interested in this property?</p><h2>Request details or a visit</h2><p>Your enquiry goes through OngoleProperty.com. Private owner details remain protected unless an approved visibility rule permits them.</p><EnquiryForm propertyReference={property.reference} propertyTitle={property.title} propertyId={property.id} captchaSiteKey={process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY}/><div className="contact-options"><a href={publicPhoneHref}>Call {contact?.label||"OngoleProperty"}</a><a href={whatsappHref} target="_blank" rel="noreferrer">WhatsApp {contact?.label||"our team"}</a></div>{sidebarAd&&<AdSlot title={sidebarAd.title} image={sidebarAd.image} alt={sidebarAd.alt} href={sidebarAd.href} className="ad-sidebar"/>}</aside></section><div className="mobile-contact-bar"><a href={publicPhoneHref}>Call</a><a href={whatsappHref}>WhatsApp</a><a href="#enquiry">Enquire</a></div></main>
}
