import {NextRequest,NextResponse} from "next/server";
import {env} from "@/src/lib/env";
import {createSupabaseServerClient} from "@/src/lib/supabase/server";
import {checkRateLimit} from "@/src/lib/security/rate-limit";
import {requestIp} from "@/src/lib/request";

const MAX_SOURCE_BYTES=15*1024*1024;
const ALLOWED_INPUT_TYPES=new Set(["image/jpeg","image/png","image/webp"]);

function dashboardUrl(request:NextRequest,propertyId:string,result:string){const pgId=request.nextUrl.searchParams.get("context")==="pg"?request.nextUrl.searchParams.get("pgId"):null;if(pgId&&/^[0-9a-f-]{36}$/i.test(pgId))return new URL(`/dashboard/pg/${pgId}?media=${result}`,request.url);return new URL(`/dashboard/properties/${propertyId}?media=${result}`,request.url)}

export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){
  const{id}=await params,isPg=request.nextUrl.searchParams.get("context")==="pg";const rate=await checkRateLimit(`upload:${requestIp(request)}`,20,60*60_000);if(!rate.allowed)return NextResponse.json({error:"Upload limit reached. Try again later."},{status:429});
  if(!env.isSupabaseConfigured)return NextResponse.json({error:"Supabase storage is not configured."},{status:503});const origin=request.headers.get("origin");if(origin&&origin!==request.nextUrl.origin)return NextResponse.json({error:"Invalid request origin."},{status:403});
  const supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)return NextResponse.redirect(new URL(`/login?returnTo=/dashboard/properties/${id}`,request.url),303);const{data:property}=await supabase.from("properties").select("id,status").eq("id",id).eq("owner_id",auth.user.id).single();if(!property||!["draft","changes_requested"].includes(property.status))return NextResponse.json({error:"This property cannot accept uploads."},{status:403});
  const form=await request.formData();const submitted=form.getAll("image").filter((item):item is File=>item instanceof File&&item.size>0),files=isPg?submitted:submitted.slice(0,1);if(!files.length||files.some((file)=>file.size>MAX_SOURCE_BYTES||!ALLOWED_INPUT_TYPES.has(file.type)))return NextResponse.redirect(dashboardUrl(request,id,"invalid"),303);
  const{count}=await supabase.from("property_media").select("id",{count:"exact",head:true}).eq("property_id",id).eq("media_type","image");const{data:planContext}=await supabase.rpc("get_my_plan_context");const planLimit=Number((planContext as{plan?:{image_limit_per_listing?:number}}|null)?.plan?.image_limit_per_listing||0),hardLimit=isPg?6:20,limit=Math.min(hardLimit,planLimit||hardLimit);if((count??0)+files.length>limit)return NextResponse.redirect(dashboardUrl(request,id,"limit"),303);
  const storedPaths:string[]=[],storedIds:string[]=[];
  try{
    const{default:sharp}=await import("sharp");
    for(const[index,file]of files.entries()){
      const source=Buffer.from(await file.arrayBuffer()),baseImage=sharp(source,{failOn:"warning",limitInputPixels:40_000_000}).rotate().resize({width:1920,height:1920,fit:"inside",withoutEnlargement:true}),dimensions=await baseImage.clone().metadata();if(!dimensions.width||!dimensions.height)throw new Error("Image dimensions unavailable");
      const watermarkWidth=Math.max(300,Math.min(760,Math.round(dimensions.width*.48))),watermarkHeight=Math.max(44,Math.round(watermarkWidth*.09)),label=isPg?"www.ongoleproperty.com | 7788998459":"ONGOLEPROPERTY.COM";const watermark=Buffer.from(`<svg width="${watermarkWidth}" height="${watermarkHeight}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" rx="8" fill="#111827" fill-opacity="0.58"/><text x="50%" y="54%" text-anchor="middle" dominant-baseline="middle" font-family="Arial, sans-serif" font-size="${Math.round(watermarkHeight*.34)}" font-weight="700" fill="#ffffff">${label}</text></svg>`);
      const processed=await baseImage.composite([{input:watermark,gravity:isPg?"south":"southeast"}]).webp({quality:84,effort:5}).toBuffer(),output=await sharp(processed).metadata(),thumbnail=await sharp(processed).resize({width:480,height:270,fit:"cover",position:"centre",withoutEnlargement:true}).webp({quality:78,effort:5}).toBuffer(),thumbnailOutput=await sharp(thumbnail).metadata(),mediaId=crypto.randomUUID(),path=`${auth.user.id}/${id}/${mediaId}.webp`,thumbnailPath=`${auth.user.id}/${id}/${mediaId}-thumb.webp`;
      const{error:uploadError}=await supabase.storage.from("property-media").upload(path,processed,{contentType:"image/webp",cacheControl:"31536000",upsert:false});if(uploadError)throw uploadError;storedPaths.push(path);const{error:thumbnailUploadError}=await supabase.storage.from("property-media").upload(thumbnailPath,thumbnail,{contentType:"image/webp",cacheControl:"31536000",upsert:false});if(thumbnailUploadError)throw thumbnailUploadError;storedPaths.push(thumbnailPath);
      const{error:recordError}=await supabase.from("property_media").insert({id:mediaId,property_id:id,storage_path:path,original_filename:file.name.slice(0,255),mime_type:"image/webp",byte_size:processed.byteLength,width:output.width,height:output.height,processing_status:"ready",is_cover:!isPg&&(count??0)===0&&index===0,sort_order:(count??0)+index,variants:{display:{path,width:output.width,height:output.height,format:"webp"},thumbnail:{path:thumbnailPath,width:thumbnailOutput.width,height:thumbnailOutput.height,format:"webp",byte_size:thumbnail.byteLength}}});if(recordError)throw recordError;storedIds.push(mediaId);
    }
    await supabase.rpc("record_audit_event",{event_action:"media.upload",event_type:"property_media",event_reference:id,event_new:{media_ids:storedIds,count:storedIds.length,context:isPg?"pg":"property"}});return NextResponse.redirect(dashboardUrl(request,id,"uploaded"),303);
  }catch(error){if(storedPaths.length)await supabase.storage.from("property-media").remove(storedPaths);if(storedIds.length)await supabase.from("property_media").delete().in("id",storedIds);console.error("Property image processing failed",{propertyId:id,error});return NextResponse.redirect(dashboardUrl(request,id,"failed"),303)}
}
