import Image from "next/image";
import Link from "next/link";
import {Mail,MapPinned,MessageCircle,Phone} from "lucide-react";
import {EnquiryForm} from "@/src/components/enquiry-form";
import {siteConfig} from "@/src/config/site";

export function ContactPage(){
  const structuredData=[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteConfig.url},{"@type":"ListItem",position:2,name:"Contact Us",item:`${siteConfig.url}/contact`}]},{"@context":"https://schema.org","@type":"ContactPage",name:"Contact OngoleProperty.com",url:`${siteConfig.url}/contact`,description:"Contact OngoleProperty.com for property enquiries and professional property services across Ongole and Prakasam District.",mainEntity:{"@type":"Organization",name:siteConfig.name,email:siteConfig.email,telephone:siteConfig.phone,areaServed:["Ongole","Prakasam District"]}}];
  return <main id="main" className="contact-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/>
    <section className="contact-hero"><div className="shell contact-hero-grid"><div><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><b>›</b><span>Contact Us</span></nav><p className="eyebrow">Online assistance + field visits</p><h1>Talk to Ongole &amp; Prakasam District Property Professionals</h1><p>Connect with our team for buying, selling, rental, Paying Guest, NRI property services, advertising and general property enquiries.</p></div><div className="contact-hero-image"><Image src="/images/ongoleproperty-contact-property-professionals.webp" alt="Property professionals assisting a client with a property enquiry" width={1344} height={768} priority sizes="(max-width: 900px) 100vw, 50vw"/></div></div></section>
    <section className="section shell contact-layout"><div><div className="contact-card-grid"><a href={siteConfig.phoneHref}><Phone aria-hidden="true"/><span><strong>Voice Call</strong><small>Speak directly with our property team.</small><b>Call Now</b></span></a><a href={siteConfig.whatsappHref} target="_blank" rel="noreferrer"><MessageCircle aria-hidden="true"/><span><strong>WhatsApp</strong><small>Chat with our property team on WhatsApp.</small><b>Chat on WhatsApp</b></span></a><a href={`mailto:${siteConfig.email}`}><Mail aria-hidden="true"/><span><strong>General Property Enquiries</strong><small>For general questions about property services.</small><b>{siteConfig.email}</b></span></a><a href={`mailto:${siteConfig.salesEmail}`}><Mail aria-hidden="true"/><span><strong>Sales &amp; Advertising</strong><small>Property advertising, partnerships and business enquiries.</small><b>{siteConfig.salesEmail}</b></span></a><a className="nri-contact-option" href={`mailto:${siteConfig.nriEmail}`}><Mail aria-hidden="true"/><span><strong>NRI Property Services</strong><small>Dedicated assistance for NRI property requirements.</small><b>{siteConfig.nriEmail}</b></span></a></div><article className="contact-office"><MapPinned aria-hidden="true"/><div><p className="eyebrow">Our Service Area</p><h2>Online Assistance &amp; Field Visits</h2><p>{siteConfig.serviceArea}</p><p>We currently do not operate a customer-facing physical office.</p></div></article></div><section className="contact-form-card" aria-labelledby="contact-form-heading"><p className="eyebrow">Send an enquiry</p><h2 id="contact-form-heading">How can we help?</h2><p>Required fields are clearly marked. No account or sign-in is needed.</p><EnquiryForm variant="contact" captchaSiteKey={process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY}/></section></section>
  </main>;
}
