import type {Metadata} from "next";
import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {AdminNavigation} from "@/src/components/admin-navigation";
import {createSupabaseServerClient} from "@/src/lib/supabase/server";

export const dynamic="force-dynamic";export const metadata:Metadata={title:"Manage user",robots:{index:false,follow:false}};
export default async function UserDetails({params}:{params:Promise<{id:string}>}){
  const{id}=await params,supabase=await createSupabaseServerClient(),{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect(`/login?returnTo=/admin/users/${id}`);
  const[{data:read},{data:manage},{data:rolesManage}]=await Promise.all([supabase.rpc("has_permission",{required_permission:"users.read"}),supabase.rpc("has_permission",{required_permission:"users.manage"}),supabase.rpc("has_permission",{required_permission:"roles.manage"})]);if(!read)redirect("/admin");
  const[{data:user},{data:properties},{data:grants},{data:uses},{data:allRoles}]=await Promise.all([supabase.from("profiles").select("*,user_roles(roles(code,name,description))").eq("id",id).maybeSingle(),supabase.from("properties").select("id,reference_no,title,status,transaction_type,created_at").eq("owner_id",id).order("created_at",{ascending:false}).limit(100),supabase.from("property_posting_grants").select("id",{count:"exact"}).eq("user_id",id),supabase.from("property_posting_uses").select("property_id",{count:"exact"}).eq("user_id",id),rolesManage?supabase.from("roles").select("code,name,description").order("name"):{data:[]}]);if(!user)notFound();
  const assigned=new Set((user.user_roles||[]).map((row:{roles:{code?:string}|{code?:string}[]|null})=>{const role=Array.isArray(row.roles)?row.roles[0]:row.roles;return role?.code}).filter(Boolean));
  return <main id="main" className="portal-page admin-portal"><div className="shell"><nav className="breadcrumbs"><Link href="/admin/users">Users</Link><span>›</span><span>{user.reference_no}</span></nav><div className="portal-title"><div><p className="eyebrow">{user.reference_no}</p><h1>{user.full_name||"Unnamed user"}</h1><p>{user.email} · {user.mobile||"No mobile"}</p></div><i className={`status status-${user.status}`}>{user.status}</i></div><AdminNavigation/><div className="review-layout"><section className="portal-section"><h2>Profile</h2><dl className="review-facts"><div><dt>Account type</dt><dd>{user.account_type}</dd></div><div><dt>Registered</dt><dd>{new Date(user.created_at).toLocaleString("en-IN")}</dd></div><div><dt>Email verification</dt><dd>{user.email_verified?"Verified":"Pending"}</dd></div><div><dt>Posting entitlement</dt><dd>{uses?.length||0} used of {1+(grants?.length||0)}</dd></div></dl><h2>Listings</h2>{properties?.length?<ol className="activity-list">{properties.map(item=><li key={item.id}><Link href={`/admin/properties/${item.id}`}><strong>{item.title}</strong></Link><span>{item.reference_no} · {item.transaction_type} · {item.status}</span></li>)}</ol>:<p>No listings.</p>}</section><aside className="review-actions">{manage&&<><h2>Account status</h2><form className="stack-form" action={`/api/admin/users/${id}`} method="post"><input type="hidden" name="action" value="status"/><select name="status" defaultValue={user.status}>{["pending","active","suspended","blocked"].map(value=><option key={value}>{value}</option>)}</select><textarea required name="reason" minLength={3} placeholder="Reason for status change"/><button className="button">Update status</button></form><hr/><h2>Property posting</h2><p>Each click grants exactly one additional permission shared by normal properties and Paying Guest.</p><form action={`/api/admin/users/${id}`} method="post"><button className="button" name="action" value="grant_post">+1 POST PROPERTY</button></form></>}{rolesManage&&<><hr/><h2>Roles</h2>{allRoles?.map(role=><form action={`/api/admin/users/${id}`} method="post" key={role.code}><input type="hidden" name="role" value={role.code}/><button name="action" value={assigned.has(role.code)?"remove_role":"assign_role"}>{assigned.has(role.code)?"Remove":"Assign"} {role.name}</button></form>)}</>}</aside></div></div></main>;
}
