import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {DEV_JV_LABEL,isDevelopmentJv} from "@/src/config/property-catalog";
import {formatArea} from "@/src/lib/area-conversion";
import {PERMISSIONS} from "@/src/lib/auth/permissions";
import {formatPrice} from "@/src/lib/format";
import {resolvePropertyDashboardAccess} from "@/src/lib/properties/dashboard-access";
import {createSupabaseServerClient} from "@/src/lib/supabase/server";
import {youtubeVideoId} from "@/src/lib/youtube";
import type {AreaUnit,TransactionType} from "@/src/types/property";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Private property preview",robots:{index:false,follow:false}};
type Fact={label:string;value:unknown};
const present=(value:unknown)=>value!==undefined&&value!==null&&value!=="";
const label=(value:unknown)=>String(value||"").replaceAll("_"," ").replaceAll("-"," ");
function nearbyItems(value:unknown){const places=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};const names:Record<string,string>={railway_station:"Railway Station",bank:"Bank",atm:"ATM",college:"College",hospital:"Hospital",bus_depot:"RTC Depot"};const result:Fact[]=[];for(const[key,raw]of Object.entries(places)){const entries=key==="custom"&&Array.isArray(raw)?raw:[raw];for(const entry of entries){if(!entry||typeof entry!=="object"||Array.isArray(entry))continue;const item=entry as Record<string,unknown>;if(present(item.distance))result.push({label:String(item.name||names[key]||label(key)),value:`${Number(item.distance).toLocaleString("en-IN")} ${item.unit||"Meter"}`})}}return result}

export default async function OwnerPreview({params}:{params:Promise<{id:string}>}){
  const{id}=await params,supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();
  if(!auth.user)redirect(`/login?returnTo=/dashboard/properties/${id}/preview`);
  const[{data:p},{data:canReadAll},{data:media}]=await Promise.all([supabase.from("properties").select("id,owner_id,reference_no,title,status,description,transaction_type,price_inr,area_value,area_unit,locality_text,city_text,district_text,state_text,details").eq("id",id).is("deleted_at",null).maybeSingle(),supabase.rpc("has_permission",{required_permission:PERMISSIONS.propertiesRead}),supabase.from("property_media").select("id,storage_path,original_filename,sort_order").eq("property_id",id).order("sort_order")]);
  if(!p||resolvePropertyDashboardAccess({authenticatedUserId:auth.user.id,ownerId:p.owner_id,canReadAll:canReadAll===true})==="denied")notFound();
  const isAdmin=p.owner_id!==auth.user.id,editorUrl=isAdmin?`/admin/properties/${id}`:`/dashboard/properties/${id}`,paths=(media||[]).map(item=>item.storage_path),{data:signed}=paths.length?await supabase.storage.from("property-media").createSignedUrls(paths,3600):{data:[]};
  const details=p.details&&typeof p.details==="object"&&!Array.isArray(p.details)?p.details as Record<string,unknown>:{},isDevJv=isDevelopmentJv({transactionType:p.transaction_type,categorySlug:typeof details.category==="string"?details.category:undefined});
  const facts:Fact[]=[{label:"Category",value:details.category_label||details.category},{label:"Property type",value:details.property_type||details.property_type_slug},{label:"Purpose",value:p.transaction_type==="sale"?"Sale":"Rent / Lease"},{label:"Area",value:formatArea(Number(p.area_value||0),p.area_unit as AreaUnit)},{label:"Price basis / period",value:details.amount_basis||details.rent_period},{label:"Bedrooms",value:details.bedrooms},{label:"Bathrooms",value:details.bathrooms},{label:"Facing",value:details.facing},{label:"Property age",value:details.property_age},{label:"Floor",value:details.floor},{label:"Total floors",value:details.total_floors},{label:"Crop",value:details.crop_type},{label:"Soil",value:details.soil_type},{label:"Fencing",value:details.fencing},{label:"Electricity",value:details.electricity_connection},{label:"Road access",value:details.road_access}].filter(item=>present(item.value));
  const facilityLabels:Record<string,string>={parking:"Parking",power_backup:"Power Backup",generator:"Generator",security:"Security",cctv:"CCTV",lift:"Lift",fire_safety:"Fire Safety",waste_management:"Waste Management",balcony:"Balcony",pooja_room:"Pooja Room",store_room:"Store Room",servant_room:"Servant Room",gas_pipeline:"Gas Pipeline"},facilities=Object.entries(facilityLabels).filter(([key])=>details[key]===true).map(([,value])=>value),nearby=nearbyItems(details.nearby_places),videoId=youtubeVideoId(typeof details.youtube_url==="string"?details.youtube_url:undefined);
  return <main id="main"><div className="owner-preview-action"><Link className="button" href={editorUrl}>Return to Editor</Link></div><section className="inner-hero editorial"><div className="shell"><p className="eyebrow">Private owner preview · {p.reference_no}</p><h1>{p.title}</h1><p>{p.locality_text}, {p.city_text}, {p.district_text}, {p.state_text}</p><span className={`status status-${p.status}`}>{p.status.replaceAll("_"," ")}</span></div></section><section className="section shell detail-section">{signed?.length?<div className="property-grid preview-gallery">{signed.map((item,index)=><div className="property-image" key={media?.[index]?.id}>{item.signedUrl&&<Image src={item.signedUrl} alt={media?.[index]?.original_filename||p.title} width={640} height={420}/>}</div>)}</div>:<div className="empty-state compact"><p>No images uploaded yet.</p></div>}<div className="detail-title"><div><h2>Listing preview</h2>{isDevJv&&<p>{DEV_JV_LABEL}</p>}<p>{p.description}</p></div><div className="detail-price"><strong>{isDevJv&&"Present Market Price: "}{formatPrice(Number(p.price_inr||0),p.transaction_type as TransactionType)}</strong><span>{formatArea(Number(p.area_value||0),p.area_unit as AreaUnit)}</span></div></div>{facts.length>0&&<><h2>Property details</h2><dl className="fact-grid">{facts.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{label(item.value)}</dd></div>)}</dl></>}{facilities.length>0&&<><h2>Amenities &amp; facilities</h2><ul className="amenity-list">{facilities.map(item=><li key={item}>{item}</li>)}</ul></>}{nearby.length>0&&<><h2>Nearby places</h2><dl className="fact-grid">{nearby.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{String(item.value)}</dd></div>)}</dl></>}{videoId&&<><h2>Property video</h2><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={`${p.title} video preview`} loading="lazy" allowFullScreen/></div></>}<p className="form-note">This preview is private to the owner and authorized administrators. Public contact follows the approved lifecycle and expired-listing replacement rules.</p><Link className="button" href={editorUrl}>Return to Editor</Link></section></main>;
}
