import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

const pages: Record<string, { title: string; eyebrow: string; intro: string; sections: { title: string; body: string }[] }> = {
  about: { title: "Built on local knowledge and long-term trust", eyebrow: "About OngoleProperty.com", intro: "Since 2002, Kosana Associates LLP has helped people across Ongole and Prakasam District market, discover and evaluate property opportunities with clarity.", sections: [{ title: "Our role", body: "We are a corporate real estate marketing platform—not a layout developer or construction company. We connect genuine buyers, sellers, landlords, tenants, investors and NRIs through professional listing, coordination and support." }, { title: "Leadership", body: "Ravi Sankar Kota, B.Com., LL.B., leads the company with an emphasis on transparent property marketing and legally informed process support." }, { title: "Our commitment", body: "Manual listing approval, responsible contact visibility and clear transaction support are built into the operating model." }] },
  services: { title: "Property support before, during and after the decision", eyebrow: "Our services", intro: "Professional marketing and coordination across residential, commercial, agricultural, industrial, rental and NRI property needs.", sections: [{ title: "Buying & selling", body: "Requirement discovery, property marketing, buyer-seller coordination, site visit support and transaction follow-up." }, { title: "Documentation support", body: "Guidance around property documentation, preliminary verification and coordination with experienced legal professionals. This is not a substitute for independent legal due diligence." }, { title: "Property trace & recovery", body: "A specialist premium assistance service for tracing forgotten ancestral properties, inherited land, old open plots and legacy records." }] },
  contact: { title: "Talk to a local property professional", eyebrow: "Contact & support", intro: "Our digital platform accepts enquiries 24 hours a day, seven days a week. The team responds at the earliest practical opportunity.", sections: [{ title: "Voice call", body: "+91 77889 98459" }, { title: "WhatsApp", body: "+91 99887 67689" }, { title: "Office", body: "4th Lane, Bhagya Nagar, Ongole, Prakasam District, Andhra Pradesh, India." }] },
  agents: { title: "A verified local agent network", eyebrow: "Real estate agents", intro: "Verified, active property professionals can join our network and serve up to five working towns with declared specialisations.", sections: [{ title: "Verification first", body: "Only agents reviewed by an administrator and marked verified and active may appear publicly." }, { title: "Professional profiles", body: "Profiles can include service towns, property specialisations, years of experience, office address and an administrator-reviewed introduction." }] },
  "paying-guest": { title: "Paying guest and co-living in Ongole", eyebrow: "PG accommodation", intro: "Discover reviewed men’s PG, women’s PG, family PG and co-living options with transparent facilities and house rules.", sections: [{ title: "Practical filters", body: "Search by category, monthly rent, room type, food, furnishing, bathroom type and occupant preference." }, { title: "Same approval standards", body: "PG listings inherit the same image processing, enquiry management, SEO, audit and security architecture as property listings." }] },
  privacy: { title: "Privacy policy", eyebrow: "Your information", intro: "OngoleProperty.com collects only the information needed to provide accounts, listings, enquiries and support, subject to applicable law and platform policy.", sections: [{ title: "How information is used", body: "Information may be used to manage accounts and listings, respond to enquiries, coordinate services, prevent fraud, maintain security and improve the platform." }, { title: "Contact privacy", body: "Private owner contact information is not exposed in public pages, metadata, source, structured data or unauthorised API responses." }, { title: "Your choices", body: "Users may request correction or deletion subject to legal, audit, security and legitimate business retention requirements." }] },
  terms: { title: "Terms & conditions", eyebrow: "Platform terms", intro: "Using OngoleProperty.com means agreeing to provide accurate information, use the service lawfully and independently verify property, legal and financial details before a transaction.", sections: [{ title: "Listings", body: "Owners and authorised representatives are responsible for submitted descriptions, prices, photographs and documents. OngoleProperty.com may review, edit, reject, suspend, archive or remove listings." }, { title: "Verification", body: "Preliminary review does not replace independent title, encumbrance, approval, survey, condition, tax, finance or legal verification." }, { title: "Platform role", body: "OngoleProperty.com acts as a real estate marketing platform and facilitator. Transaction decisions remain with the involved parties and their professional advisers." }] },
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const page = pages[slug]; return page ? { title: page.title, description: page.intro, alternates: { canonical: `/${slug}` } } : {}; }
export function generateStaticParams() { return Object.keys(pages).map((slug) => ({ slug })); }
export default async function ContentPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug]; if (!page) notFound(); return <main id="main"><section className="inner-hero editorial"><div className="shell"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></div></section><section className="section shell editorial-grid"><div>{page.sections.map((section) => <article key={section.title}><h2>{section.title}</h2><p>{section.body}</p></article>)}</div><aside><p className="eyebrow">Need assistance?</p><h2>Speak with our team</h2><p>Property enquiries are accepted around the clock.</p><a className="button" href="tel:+917788998459">Call +91 77889 98459</a><Link className="arrow-link" href="/contact">All contact options →</Link></aside></section></main>; }
