import type{Metadata}from"next";
import{redirect}from"next/navigation";
import{DashboardShell,EmptyState,StatusBadge}from"@/src/components/dashboard/dashboard-shell";
import{createSupabaseServerClient}from"@/src/lib/supabase/server";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Manual payment approvals",robots:{index:false,follow:false}};
export default async function ManualApprovals(){
  const supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/login?returnTo=/admin/billing/manual");
  const[{data:allowed},{data:manage}]=await Promise.all([supabase.rpc("has_permission",{required_permission:"payments.read"}),supabase.rpc("has_permission",{required_permission:"payments.manage"})]);if(!allowed)redirect("/admin");
  const{data:items}=await supabase.from("manual_payment_requests").select("*,profiles(full_name,email),plans(name)").order("created_at",{ascending:false}).limit(100);
  const paths=(items||[]).map((item)=>item.proof_path).filter((path):path is string=>Boolean(path));const{data:signed}=paths.length?await supabase.storage.from("payment-proofs").createSignedUrls(paths,900):{data:[]};const proofUrls=new Map(paths.map((path,index)=>[path,signed?.[index]?.signedUrl]));
  return <DashboardShell variant="admin" title="Manual payment approvals" description="Review proof and activate subscriptions through one protected transaction." breadcrumbs={[{label:"Admin",href:"/admin"},{label:"Billing",href:"/admin/billing"},{label:"Manual approvals"}]}>{items?.length?<div className="manual-review-grid">{items.map((item)=>{const user=first(item.profiles),plan=first(item.plans);return <article className="dashboard-card" key={item.id}><header><div><h2>{user?.full_name||user?.email}</h2><p>{plan?.name} · {item.transaction_reference}</p></div><StatusBadge status={item.status}/></header><dl className="review-facts"><div><dt>Amount</dt><dd>₹{Number(item.amount).toLocaleString("en-IN")}</dd></div><div><dt>Mode</dt><dd>{item.payment_mode}</dd></div><div><dt>Paid on</dt><dd>{item.payment_date}</dd></div><div><dt>Submitted</dt><dd>{new Date(item.created_at).toLocaleDateString("en-IN")}</dd></div><div><dt>Proof</dt><dd>{item.proof_path&&proofUrls.get(item.proof_path)?<a href={proofUrls.get(item.proof_path)} target="_blank" rel="noreferrer">Open secure proof</a>:"Not supplied"}</dd></div></dl>{item.note&&<p>{item.note}</p>}{manage&&["pending","clarification_requested"].includes(item.status)&&<form className="stack-form" action={`/api/admin/billing/manual/${item.id}`} method="post"><label>Review note<textarea required name="note" minLength={3}/></label><div className="dashboard-title-actions"><button className="button" name="decision" value="approve">Approve</button><button className="button button-light" name="decision" value="request_clarification">Request clarification</button><button className="danger-button" name="decision" value="reject">Reject</button></div></form>}</article>})}</div>:<EmptyState title="No manual payments" description="New payment proof submissions appear here."/>}</DashboardShell>
}
function first<T>(value:T|T[]|null):T|undefined{return Array.isArray(value)?value[0]:value||undefined}
