import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {PERMISSIONS} from "@/src/lib/auth/permissions";
import {resolvePropertyDashboardAccess} from "@/src/lib/properties/dashboard-access";
import {createSupabaseServerClient} from "@/src/lib/supabase/server";
import {youtubeVideoId} from "@/src/lib/youtube";
import {normalizePgRentBasis,PG_RENT_BASIS_LABELS} from "@/src/types/pg";

export const metadata:Metadata={title:"Preview PG",robots:{index:false,follow:false}};
export const dynamic="force-dynamic";
function nearbyItems(value:unknown){const places=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};const labels:Record<string,string>={railway_station:"Railway Station",bank:"Bank",atm:"ATM",college:"College",hospital:"Hospital",bus_depot:"RTC Depot"};const result:{name:string;value:string}[]=[];for(const[key,raw]of Object.entries(places)){const entries=key==="custom"&&Array.isArray(raw)?raw:[raw];for(const entry of entries){if(!entry||typeof entry!=="object"||Array.isArray(entry))continue;const item=entry as Record<string,unknown>,distance=Number(item.distance);if(Number.isFinite(distance))result.push({name:String(item.name||labels[key]||key.replaceAll("_"," ")),value:`${distance.toLocaleString("en-IN")} ${item.unit||"Meter"}`})}}return result}

export default async function PreviewPg({params}:{params:Promise<{id:string}>}){
  const{id}=await params,supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect(`/login?returnTo=/dashboard/pg/${id}/preview`);
  const[{data:pg},{data:canReadAll}]=await Promise.all([supabase.from("pg_listings").select("*,pg_room_types(*),properties!inner(id,owner_id,reference_no,description,locality_text,city_text,district_text,state_text,status,latitude,longitude,property_media(id,storage_path,original_filename,sort_order))").eq("id",id).maybeSingle(),supabase.rpc("has_permission",{required_permission:PERMISSIONS.pgRead})]);if(!pg)notFound();const property=Array.isArray(pg.properties)?pg.properties[0]:pg.properties;if(!property||resolvePropertyDashboardAccess({authenticatedUserId:auth.user.id,ownerId:property.owner_id,canReadAll:canReadAll===true})==="denied")notFound();
  const isAdmin=property.owner_id!==auth.user.id,editorUrl=isAdmin?`/admin/pg/${id}`:`/dashboard/pg/${id}`,media=[...(property.property_media||[])].sort((a,b)=>a.sort_order-b.sort_order),{data:signed}=media.length?await supabase.storage.from("property-media").createSignedUrls(media.map(item=>item.storage_path),3600):{data:[]},details=pg.details&&typeof pg.details==="object"&&!Array.isArray(pg.details)?pg.details as Record<string,unknown>:{},nearby=nearbyItems(details.nearby_places),rentBasis=PG_RENT_BASIS_LABELS[normalizePgRentBasis(details.rent_basis)];pg.category=`${pg.category} · ${rentBasis}`;
  return <main id="main" className="detail-page"><div className="owner-preview-action"><Link className="button" href={editorUrl}>Return to Editor</Link></div><div className="shell"><div className="preview-banner">Private owner preview</div><p className="eyebrow">{property.reference_no} · {property.status}</p><h1>{pg.pg_name}</h1>{signed?.length?<div className="property-grid preview-gallery">{signed.map((item,index)=><div className="property-image" key={media[index]?.id}>{item.signedUrl&&<Image src={item.signedUrl} alt={media[index]?.original_filename||pg.pg_name} width={640} height={420}/>}</div>)}</div>:<div className="empty-state compact"><p>No images uploaded yet.</p></div>}<p>{pg.address_line}, {property.locality_text}, {property.city_text}, {property.district_text}, {property.state_text}</p><p>{property.description}</p><dl className="fact-grid"><div><dt>Category</dt><dd>{String(pg.category).replaceAll("_"," ")}</dd></div><div><dt>Starting rent</dt><dd>₹{Number(pg.rent_per_bed).toLocaleString("en-IN")} / bed / month</dd></div>{pg.capacity&&<div><dt>Total capacity</dt><dd>{pg.capacity}</dd></div>}{pg.food_type&&<div><dt>Food</dt><dd>{pg.food_type}</dd></div>}{details.facing&&<div><dt>Facing</dt><dd>{String(details.facing)}</dd></div>}{details.landmark&&<div><dt>Landmark</dt><dd>{String(details.landmark)}</dd></div>}</dl><h2>Rooms</h2><div className="feature-grid">{pg.pg_room_types?.map((room:{id:string;name:string;sharing_type:string;available_beds:number;monthly_rent:number})=><article key={room.id}><h3>{room.name}</h3><p>{room.sharing_type.replaceAll("_"," ")} · {room.available_beds} beds available</p><strong>₹{Number(room.monthly_rent).toLocaleString("en-IN")}/month</strong></article>)}</div>{pg.amenities?.length>0&&<><h2>Amenities</h2><ul className="amenity-list">{pg.amenities.map((item:string)=><li key={item}>{item}</li>)}</ul></>}{nearby.length>0&&<><h2>Nearby places</h2><dl className="fact-grid">{nearby.map(item=><div key={item.name}><dt>{item.name}</dt><dd>{item.value}</dd></div>)}</dl></>}{pg.house_rules?.length>0&&<><h2>House rules</h2><ul className="highlight-list">{pg.house_rules.map((item:string)=><li key={item}>{item}</li>)}</ul></>}{pg.video_urls?.map((video:string)=>{const videoId=youtubeVideoId(video);return videoId?<section className="detail-section" key={video}><h2>PG video</h2><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={`${pg.pg_name} video preview`} loading="lazy" allowFullScreen/></div></section>:null})}<p className="form-note">This preview is private to the owner and authorized administrators. Public contact follows the approved lifecycle and expired-listing replacement rules.</p><Link className="button" href={editorUrl}>Return to Editor</Link></div></main>;
}
