"use client";

import Script from "next/script";
import {useMemo,useState} from "react";
import {COUNTRY_CALLING_CODES} from "@/src/data/country-calling-codes";

type Variant="default"|"contact"|"nri";
const enquiryTypes=["Buy / Sell Property","Rent / Lease","Paying Guest","NRI Services","Advertising / Business Enquiry","General Enquiry"];
export function EnquiryForm({propertyReference="",propertyTitle,propertyId,entityType="property",captchaSiteKey,defaultMessage,variant="default"}:{propertyReference?:string;propertyTitle?:string;propertyId?:string;entityType?:"property"|"pg";captchaSiteKey?:string;defaultMessage?:string;variant?:Variant}){
  const[state,setState]=useState<{status:"idle"|"loading"|"success"|"error";message?:string}>({status:"idle"}),[foreign,setForeign]=useState(false),[messageValue,setMessageValue]=useState(defaultMessage||(propertyTitle?`I am interested in ${propertyTitle}${propertyReference?` (${propertyReference})`:""}. Please contact me.`:"")),[countryCode,setCountryCode]=useState("+1"),[countrySearch,setCountrySearch]=useState("");
  const wordCount=useMemo(()=>messageValue.trim()?messageValue.trim().split(/\s+/).length:0,[messageValue]);
  const filteredCountries=useMemo(()=>{const query=countrySearch.trim().toLowerCase();return query?COUNTRY_CALLING_CODES.filter(([country,code])=>country.toLowerCase().includes(query)||code.includes(query)).slice(0,80):COUNTRY_CALLING_CODES},[countrySearch]);
  return <form id="enquiry" className="enquiry-form" onSubmit={async(event)=>{event.preventDefault();if(wordCount>250){setState({status:"error",message:"Please keep your message within 250 words."});return}setState({status:"loading"});const form=event.currentTarget;try{const response=await fetch("/api/enquiries",{method:"POST",body:new FormData(form),headers:{Accept:"application/json"}});const result=await response.json()as{error?:string;reference?:string};if(!response.ok)throw new Error(result.error||"Unable to send enquiry.");form.reset();setForeign(false);setCountryCode("+1");setCountrySearch("");setMessageValue("");const path=window.location.pathname.split("/").filter(Boolean),resolvedType=path[0]==="paying-guest"?"pg":entityType;void fetch("/api/analytics/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(propertyId?{eventType:"enquiry_submitted",entityType:resolvedType,entityId:propertyId}:{eventType:"enquiry_submitted",entityType:resolvedType,metadata:{slug:path[1]||path[0]||""}}),keepalive:true});setState({status:"success",message:"Thank you. Your enquiry has been received. Our team will get back to you shortly."})}catch{setState({status:"error",message:"We could not send your enquiry right now. Please try again, call or WhatsApp our team."})}}}>
    <input type="hidden" name="propertyReference" value={propertyReference}/><input type="hidden" name="isForeign" value={foreign?"true":"false"}/><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>
    <label>Full Name<input required name="name" autoComplete="name" minLength={2} maxLength={100}/></label>
    {!foreign?<label>Mobile Number <span>(India +91)</span><input required name="mobile" type="tel" inputMode="numeric" autoComplete="tel" pattern="[6-9][0-9]{9}" aria-describedby="enquiry-mobile-help"/><small id="enquiry-mobile-help">Enter a valid 10-digit Indian mobile number.</small></label>:<fieldset className="foreign-mobile"><legend>Foreign mobile number</legend><label>Search country<input type="search" value={countrySearch} onChange={event=>setCountrySearch(event.target.value)} placeholder="Country name or calling code" autoComplete="off"/></label><label>Country / calling code<select required value={countryCode} onChange={event=>setCountryCode(event.target.value)}>{filteredCountries.length?filteredCountries.map(([country,code])=><option value={code} key={`${country}-${code}`}>{country} ({code})</option>):<option disabled>No matching country</option>}</select></label><input type="hidden" name="countryCode" value={countryCode}/><label>Mobile number<input required name="mobile" type="tel" inputMode="tel" autoComplete="tel" pattern="[0-9]{6,14}" aria-describedby="international-mobile-help"/><small id="international-mobile-help">Enter the national number without the country code.</small></label></fieldset>}
    <label className="foreign-toggle"><input type="checkbox" checked={foreign} onChange={event=>setForeign(event.target.checked)}/> NRI? Use a foreign mobile number</label>
    <label>Email Address <span>{variant==="nri"?"":"(optional)"}</span><input required={variant==="nri"} name="email" type="email" autoComplete="email"/></label>
    {variant==="contact"&&<label>Enquiry Type<select required name="enquiryType" defaultValue="General Enquiry">{enquiryTypes.map(type=><option key={type}>{type}</option>)}</select></label>}
    {variant==="nri"&&<label>Property Requirement<input required name="propertyRequirement" minLength={3} maxLength={200} placeholder="Buying, selling, tracing, rental or other assistance"/></label>}
    <label>Message<textarea required name="message" rows={5} minLength={5} value={messageValue} onChange={event=>setMessageValue(event.target.value)} aria-describedby="message-count"/></label><small id="message-count" className={wordCount>250?"word-count error":"word-count"}>{wordCount} / 250 words</small>
    {captchaSiteKey&&<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer/><div className="cf-turnstile" data-sitekey={captchaSiteKey}/></>}
    <button className="button" type="submit" disabled={state.status==="loading"||wordCount>250}>{state.status==="loading"?"Sending…":variant==="nri"?"Send Your Requirement":"Send Enquiry"}</button><p className={`form-response ${state.status}`} role={state.status==="error"?"alert":state.status==="success"?"status":undefined} aria-live="polite">{state.message}</p>
  </form>;
}
