"use client";

import Image from "next/image";
import Link from "next/link";
import { ChevronLeft, ChevronRight, Pause, Play } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { PropertySearch } from "@/src/components/property-search";
import type {PropertyCatalogData} from "@/src/config/property-catalog";

const slides=[{label:"Apartment",image:"/images/hero/apartment.webp",alt:"Contemporary apartment community in warm morning light",title:"Apartments made easier to discover.",copy:"Browse professionally reviewed apartment opportunities across Ongole."},{label:"Villa",image:"/images/hero/villa.webp",alt:"Contemporary villa with landscaped garden",title:"More room for the life ahead.",copy:"Explore villas and independent homes with practical local support."},{label:"Open Plot",image:"/images/hero/open-plot.webp",alt:"Residential open plots with an approach road",title:"Find the right place to build.",copy:"Compare open plots by location, area, access and budget."},{label:"Commercial",image:"/images/hero/commercial.webp",alt:"Modern commercial office property",title:"Space for the next business move.",copy:"Discover shops, offices and commercial opportunities in growing locations."},{label:"Agricultural Land",image:"/images/hero/agricultural.webp",alt:"Agricultural fields in Prakasam District",title:"Land opportunities, understood locally.",copy:"Search agricultural and farm land across Prakasam District."}];

export function HeroSlider({catalog}:{catalog:PropertyCatalogData}){
  const [active,setActive]=useState(0),[paused,setPaused]=useState(false),[reducedMotion,setReducedMotion]=useState(false);const pointerStart=useRef<number|null>(null);
  useEffect(()=>{const query=window.matchMedia("(prefers-reduced-motion: reduce)");const update=()=>setReducedMotion(query.matches);update();query.addEventListener("change",update);return()=>query.removeEventListener("change",update)},[]);
  useEffect(()=>{if(paused||reducedMotion)return;const timer=window.setInterval(()=>setActive((index)=>(index+1)%slides.length),5000);return()=>window.clearInterval(timer)},[paused,reducedMotion]);
  const move=(direction:number)=>{setPaused(true);setActive((index)=>(index+direction+slides.length)%slides.length)};const slide=slides[active];
  return <section className="hero-slider" aria-roledescription="carousel" aria-label="Property categories" tabIndex={0} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={(event)=>!event.currentTarget.contains(event.relatedTarget)&&setPaused(false)} onKeyDown={(event)=>{if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1)}} onPointerDown={(event)=>{pointerStart.current=event.clientX;setPaused(true)}} onPointerUp={(event)=>{if(pointerStart.current===null)return;const distance=event.clientX-pointerStart.current;if(Math.abs(distance)>45)move(distance>0?-1:1);pointerStart.current=null}}>
    <div className="hero-slides"><div id="hero-slide-panel" role="tabpanel" aria-labelledby={`hero-tab-${active}`} key={slide.label} className="hero-slide is-active"><Image src={slide.image} alt={slide.alt} fill priority={active===0} loading={active===0?"eager":"lazy"} sizes="100vw"/></div></div><div className="hero-overlay"/>
    <div className="shell hero-slider-content"><p className="eyebrow">Ongole&apos;s trusted property platform</p><p className="slide-label">{slide.label}</p><h1>Buy, Sell, Rent &amp; Invest in Properties in Ongole</h1><p className="hero-copy">{slide.copy}</p><div className="hero-actions"><Link className="button button-light" href="/properties">Search Properties</Link><Link className="button hero-post-button" href="/post-property">Post Property</Link></div><PropertySearch catalog={catalog}/><div className="hero-proof"><span><strong>Since 2002</strong> trusted local presence</span><span><strong>Manual</strong> listing review</span><span><strong>Local</strong> property coordination</span></div></div>
    <button className="slider-control previous" type="button" onClick={()=>move(-1)} aria-label="Previous property category"><ChevronLeft aria-hidden="true"/></button><button className="slider-control next" type="button" onClick={()=>move(1)} aria-label="Next property category"><ChevronRight aria-hidden="true"/></button>
    <div className="slider-navigation"><div className="slider-dots" role="tablist" aria-label="Choose property category">{slides.map((item,index)=><button id={`hero-tab-${index}`} key={item.label} role="tab" aria-selected={index===active} aria-controls="hero-slide-panel" tabIndex={index===active?0:-1} aria-label={`Show ${item.label}`} onClick={()=>{setPaused(true);setActive(index)}}/>)}</div><button className="slider-pause" type="button" aria-pressed={paused||reducedMotion} onClick={()=>setPaused((value)=>!value)} disabled={reducedMotion} aria-label={reducedMotion?"Automatic slide rotation disabled by reduced-motion preference":paused?"Resume automatic slide rotation":"Pause automatic slide rotation"}>{paused||reducedMotion?<Play aria-hidden="true"/>:<Pause aria-hidden="true"/>}</button></div><p className="sr-only" aria-live="polite">Showing {slide.label}</p>
  </section>;
}
