"use client";

import Image from "next/image";
import Link from "next/link";
import { Pause, Play } from "lucide-react";
import { useEffect, useState } from "react";

const slides=[{name:"Paying Guest for Men",image:"/images/paying-guest/ram-tej-pg-men.webp",alt:"Bright reception and shared spaces at Ram Tej Paying Guest for Men"},{name:"Paying Guest for Women",image:"/images/paying-guest/ram-tej-pg-women.webp",alt:"Bright reception and study spaces at Ram Tej Paying Guest for Women"},{name:"Co-Living",image:"/images/paying-guest/ram-tej-co-living.webp",alt:"Modern shared work and lounge spaces at Ram Tej Co-Living"}] as const;
export function PgHero(){const[active,setActive]=useState(0),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false);useEffect(()=>{const query=matchMedia("(prefers-reduced-motion: reduce)"),update=()=>setReduced(query.matches);update();query.addEventListener("change",update);return()=>query.removeEventListener("change",update)},[]);useEffect(()=>{if(paused||reduced)return;const timer=setInterval(()=>setActive((value)=>(value+1)%slides.length),5000);return()=>clearInterval(timer)},[paused,reduced]);return <section className="pg-hero" aria-roledescription="carousel" aria-label="Paying guest categories" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={(event)=>!event.currentTarget.contains(event.relatedTarget)&&setPaused(false)}><div className="pg-hero-media">{slides.map((slide,index)=><Image key={slide.image} className={index===active?"is-active":""} src={slide.image} alt={index===active?slide.alt:""} fill priority={index===0} loading={index===0?"eager":"lazy"} sizes="100vw"/>)}</div><div className="pg-hero-overlay"/><div className="shell pg-hero-content"><p className="eyebrow">Paying guest accommodation</p><h1>Find a trusted PG or co-living space</h1><p>Search reviewed accommodation across Ongole and Prakasam District by location, category, rent, food, facilities and current availability.</p><div className="button-row"><a className="button" href="#pg-search">Search Paying Guests</a><Link className="button button-light" href="/dashboard/pg/new">List Your PG</Link></div><strong>{slides[active].name}</strong></div><div className="pg-hero-controls" role="group" aria-label="PG hero controls">{slides.map((slide,index)=><button key={slide.name} type="button" aria-label={`Show ${slide.name}`} aria-pressed={active===index} onClick={()=>{setActive(index);setPaused(true)}}/>)}<button className="pg-pause" type="button" onClick={()=>setPaused((value)=>!value)} aria-label={paused||reduced?"Resume PG image rotation":"Pause PG image rotation"} disabled={reduced}>{paused||reduced?<Play aria-hidden="true"/>:<Pause aria-hidden="true"/>}</button></div><p className="sr-only" aria-live="polite">Showing {slides[active].name}</p></section>}
