"use client";

import { Filter, RotateCcw, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { fallbackPropertyCatalog, furnishingOptions, typesFromCatalog, type PropertyCatalogData } from "@/src/config/property-catalog";
import {activeFilterEntries} from "@/src/lib/properties/filters";
import type { PropertyFilters } from "@/src/types/property";

const landTypes=new Set(["open-plot","commercial-open-plot","agricultural-land","farm-land"]);
export function PropertyFilterForm({filters,catalog=fallbackPropertyCatalog,basePath="/properties",fixedPurpose}:{filters:PropertyFilters;catalog?:PropertyCatalogData;basePath?:string;fixedPurpose?:"sale"|"rent"}){
  const [open,setOpen]=useState(false);const [category,setCategory]=useState(filters.category||"");
  const selectedType=filters.type||"";const isLand=category==="agricultural"||landTypes.has(selectedType);const activeCount=activeFilterEntries(filters).filter(([key])=>key!=="purpose").length;const applicableAmenities=isLand?catalog.amenities.filter((amenity)=>["Road Access","Water Supply"].includes(amenity)):catalog.amenities;const form=<form className="filter-form" action={basePath} method="get" onSubmit={(event)=>{const controls=event.currentTarget.elements,min=controls.namedItem("minArea") as HTMLInputElement|null,max=controls.namedItem("maxArea") as HTMLInputElement|null,unit=controls.namedItem("areaUnit") as HTMLSelectElement|null;if(!min?.value&&!max?.value&&unit)unit.disabled=true}}><div className="filter-form-head"><h2>Filter properties</h2><button type="button" onClick={()=>setOpen(false)} aria-label="Close filters"><X/></button></div>
    <label>Keyword<input name="q" defaultValue={filters.keyword} placeholder="Title or property ID"/></label>
    {fixedPurpose?<input type="hidden" name="purpose" value={fixedPurpose}/>:<label>Transaction<select name="purpose" defaultValue={filters.purpose||""}><option value="">Sale, rent or lease</option><option value="sale">Sale</option><option value="rent">Rent</option><option value="lease">Lease</option></select></label>}
    <label>Category<select name="category" value={category} onChange={(event)=>setCategory(event.target.value)}><option value="">All categories</option>{catalog.categories.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
    <label>Property type<select name="type" defaultValue={filters.type||""}><option value="">All property types</option>{typesFromCatalog(catalog,category).map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
    <label>Mandal/Town<select name="city" defaultValue={filters.city||""}><option value="">Select Mandal/Town</option>{catalog.locations.map((location)=><option key={location} value={location}>{location}</option>)}</select></label><label>Location<input name="locality" defaultValue={filters.locality||filters.location} placeholder="e.g. Bhagya Nagar"/></label>
    <fieldset><legend>Budget (₹)</legend><div className="field-pair"><label>From<input name="minPrice" defaultValue={filters.minPrice} type="number" min="0" step="10000" aria-label="Budget from in rupees"/></label><label>To<input name="maxPrice" defaultValue={filters.maxPrice} type="number" min="0" step="10000" aria-label="Budget to in rupees"/></label></div></fieldset>
    <fieldset><legend>Area</legend><label>Unit<select name="areaUnit" defaultValue={filters.areaUnit||"sq_ft"}><option value="sq_ft">Square feet</option><option value="sq_yd">Square yards</option><option value="sq_m">Square metres</option><option value="cent">Cents</option><option value="acre">Acres</option><option value="gunta">Guntas</option></select></label><div className="field-pair"><label>From<input name="minArea" defaultValue={filters.minArea} type="number" min="0" aria-label="Minimum area"/></label><label>To<input name="maxArea" defaultValue={filters.maxArea} type="number" min="0" aria-label="Maximum area"/></label></div></fieldset>
    {!isLand&&<div className="field-pair"><label>Bedrooms<select name="bedrooms" defaultValue={filters.bedrooms||""}><option value="">Any</option>{[1,2,3,4,5].map((value)=><option key={value}>{value}</option>)}</select></label><label>Bathrooms<select name="bathrooms" defaultValue={filters.bathrooms||""}><option value="">Any</option>{[1,2,3,4,5].map((value)=><option key={value}>{value}</option>)}</select></label></div>}
    {!isLand&&<><label>Facing<select name="facing" defaultValue={filters.facing||""}><option value="">Any facing</option>{catalog.facings.map((value)=><option key={value}>{value}</option>)}</select></label><label>Furnishing<select name="furnishing" defaultValue={filters.furnishing||""}><option value="">Any furnishing</option>{furnishingOptions.map((value)=><option key={value}>{value}</option>)}</select></label><label>Ownership<select name="ownership" defaultValue={filters.ownership||""}><option value="">Any ownership</option><option>Freehold</option><option>Leasehold</option><option>Power of Attorney</option></select></label></>}
    <fieldset><legend>Listing status</legend><div className="check-grid"><label><input type="checkbox" name="featured" value="true" defaultChecked={filters.featuredOnly}/>Featured</label><label><input type="checkbox" name="new" value="true" defaultChecked={filters.newOnly}/>New listings</label>{fixedPurpose==="rent"&&<label><input type="checkbox" name="available" value="true" defaultChecked={filters.availableOnly}/>Available now</label>}</div></fieldset>
    <fieldset><legend>Amenities</legend><div className="check-grid">{applicableAmenities.map((amenity)=><label key={amenity}><input type="checkbox" name="amenities" value={amenity} defaultChecked={filters.amenities?.includes(amenity)}/>{amenity}</label>)}</div></fieldset>
    <input type="hidden" name="sort" value={filters.sort}/><button className="button" type="submit">Apply filters</button><Link className="clear-filters" href={basePath}><RotateCcw size={15}/>Clear all filters</Link>
  </form>;
  return <><button className="mobile-filter-button" type="button" onClick={()=>setOpen(true)} aria-expanded={open} aria-controls="property-filters"><Filter size={18}/>Filters{activeCount>0?` (${activeCount})`:""}</button><aside id="property-filters" className={`filter-sidebar ${open?"is-open":""}`}>{form}</aside>{open&&<button className="filter-backdrop" onClick={()=>setOpen(false)} aria-label="Close filters"/>}</>;
}
