"use client";

import Image from "next/image";
import { ChevronLeft, ChevronRight, Maximize, Minus, Plus, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import type { PropertyMedia } from "@/src/types/property";

export function PropertyGallery({media,title}:{media:PropertyMedia[];title:string}){const images=media.slice(0,6);const [active,setActive]=useState(0);const [open,setOpen]=useState(false);const [zoom,setZoom]=useState(1);const touch=useRef<number|null>(null);const move=useCallback((direction:number)=>{setActive((index)=>(index+direction+images.length)%images.length);setZoom(1)},[images.length]);
  useEffect(()=>{if(!open)return;const handler=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1)};document.body.classList.add("gallery-open");document.addEventListener("keydown",handler);return()=>{document.body.classList.remove("gallery-open");document.removeEventListener("keydown",handler)}},[open,move]);
  if(!images.length)return null;const current=images[active];return <section className="property-gallery" aria-label="Property image gallery"><button className="gallery-main" onClick={()=>setOpen(true)} aria-label="Open full-screen image viewer"><Image src={current.url} alt={current.alt||`${title} image ${active+1}`} fill priority sizes="(max-width: 900px) 100vw, 800px"/><span><Maximize size={16}/>View gallery</span></button>{images.length>1&&<div className="gallery-thumbnails">{images.map((image,index)=><button key={image.id} className={index===active?"is-active":""} onClick={()=>setActive(index)} aria-label={`Show image ${index+1}`}><Image src={image.url} alt="" fill sizes="120px"/></button>)}</div>}
    {open&&<div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label="Full-screen property images" onTouchStart={(event)=>touch.current=event.touches[0].clientX} onTouchEnd={(event)=>{if(touch.current===null)return;const delta=event.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>50)move(delta>0?-1:1);touch.current=null}}><div className="lightbox-toolbar"><span>{active+1} / {images.length}</span><button onClick={()=>setZoom((value)=>Math.max(1,value-.25))} aria-label="Zoom out"><Minus/></button><button onClick={()=>setZoom((value)=>Math.min(3,value+.25))} aria-label="Zoom in"><Plus/></button><button onClick={()=>setOpen(false)} aria-label="Close gallery"><X/></button></div><div className="lightbox-image" style={{"--gallery-zoom":zoom} as React.CSSProperties}><Image src={current.url} alt={current.alt||`${title} image ${active+1}`} fill sizes="100vw"/></div>{images.length>1&&<><button className="lightbox-nav previous" onClick={()=>move(-1)} aria-label="Previous image"><ChevronLeft/></button><button className="lightbox-nav next" onClick={()=>move(1)} aria-label="Next image"><ChevronRight/></button></>}</div>}
  </section>}
