"use client";

import Image from "next/image";
import { ChevronLeft, ChevronRight, Maximize, Minus, Plus, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import type { PropertyMedia } from "@/src/types/property";

export function PropertyGallery({media,title}:{media:PropertyMedia[];title:string}){const images=media.slice(0,6);const [active,setActive]=useState(0);const [open,setOpen]=useState(false);const [zoom,setZoom]=useState(1);const touch=useRef<number|null>(null),opener=useRef<HTMLButtonElement|null>(null),dialog=useRef<HTMLDivElement|null>(null),closeButton=useRef<HTMLButtonElement|null>(null);const move=useCallback((direction:number)=>{setActive((index)=>(index+direction+images.length)%images.length);setZoom(1)},[images.length]);
  useEffect(()=>{if(!open)return;const trigger=opener.current;const handler=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1);if(event.key==="Tab"){const controls=[...(dialog.current?.querySelectorAll<HTMLElement>("button,[href]")||[])].filter((item)=>!item.hasAttribute("disabled"));if(!controls.length)return;const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.body.classList.add("gallery-open");document.addEventListener("keydown",handler);closeButton.current?.focus();return()=>{document.body.classList.remove("gallery-open");document.removeEventListener("keydown",handler);trigger?.focus()}},[open,move]);
  if(!images.length)return null;const current=images[active];return <section className="property-gallery" aria-label="Property image gallery"><button ref={opener} type="button" className="gallery-main" onClick={()=>setOpen(true)} aria-label="Open full-screen image viewer"><Image src={current.url} alt={current.alt||`${title} image ${active+1}`} fill priority sizes="(max-width: 900px) 100vw, 800px"/><span><Maximize aria-hidden="true" size={16}/>View gallery</span></button>{images.length>1&&<div className="gallery-thumbnails">{images.map((image,index)=><button type="button" key={image.id} className={index===active?"is-active":""} onClick={()=>setActive(index)} aria-pressed={index===active} aria-label={`Show image ${index+1}`}><Image src={image.url} alt="" fill sizes="120px"/></button>)}</div>}
    {open&&<div ref={dialog} className="gallery-lightbox" role="dialog" aria-modal="true" aria-labelledby="gallery-dialog-title" onTouchStart={(event)=>touch.current=event.touches[0].clientX} onTouchEnd={(event)=>{if(touch.current===null)return;const delta=event.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>50)move(delta>0?-1:1);touch.current=null}}><h2 className="sr-only" id="gallery-dialog-title">{title} image gallery</h2><div className="lightbox-toolbar"><span aria-live="polite">{active+1} / {images.length}</span><button type="button" onClick={()=>setZoom((value)=>Math.max(1,value-.25))} aria-label="Zoom out"><Minus aria-hidden="true"/></button><button type="button" onClick={()=>setZoom((value)=>Math.min(3,value+.25))} aria-label="Zoom in"><Plus aria-hidden="true"/></button><button ref={closeButton} type="button" onClick={()=>setOpen(false)} aria-label="Close gallery"><X aria-hidden="true"/></button></div><div className="lightbox-image" style={{"--gallery-zoom":zoom} as React.CSSProperties}><Image src={current.url} alt={current.alt||`${title} image ${active+1}`} fill sizes="100vw"/></div>{images.length>1&&<><button type="button" className="lightbox-nav previous" onClick={()=>move(-1)} aria-label="Previous image"><ChevronLeft aria-hidden="true"/></button><button type="button" className="lightbox-nav next" onClick={()=>move(1)} aria-label="Next image"><ChevronRight aria-hidden="true"/></button></>}</div>}
  </section>}
