import Link from "next/link";
import {Facebook,Instagram,Linkedin,Mail,MapPinned,MessageCircle,Phone} from "lucide-react";
import {siteConfig} from "@/src/config/site";

const propertyLinks=[["/properties","All Properties"],["/properties-for-sale","Properties for Sale"],["/properties-for-rent","Properties for Rent / Lease"],["/paying-guest","Paying Guest"]] as const;
const serviceLinks=[["/properties-for-sale","Property Buying & Selling"],["/properties-for-rent","Property Rental / Lease"],["/paying-guest","Paying Guest"],["/nri-services-ongole","NRI Property Services"],["/advertise-with-us","Advertising / Business Enquiry"],["/nri-services-ongole#property-tracing","Property Tracing"]] as const;
const companyLinks=[["/","Home"],["/about","About Us"],["/agents","Real Estate Agents"],["/contact","Contact Us"]] as const;
const policyLinks=[["/privacy-policy","Privacy Policy"],["/terms-and-conditions","Terms & Conditions"],["/disclaimer","Disclaimer"],["/property-listing-policy","Property Listing Policy"],["/membership-policy","Membership Policy"],["/advertisement-policy","Advertisement Policy"],["/cookie-policy","Cookie Policy"],["/copyright-policy","Copyright Policy"],["/contact-grievance-policy","Contact & Grievance Policy"]] as const;
function FooterLinks({title,links,legal=false}:{title:string;links:readonly (readonly [string,string])[];legal?:boolean}){const content=<><h3>{title}</h3>{links.map(([href,label])=><Link href={href} key={href}>{label}</Link>)}</>;return legal?<nav aria-label="Legal policies">{content}</nav>:<nav aria-label={title}>{content}</nav>}

export function SiteFooter(){
  const socials=[{label:"Facebook",href:siteConfig.social.facebook,Icon:Facebook},{label:"Instagram",href:siteConfig.social.instagram,Icon:Instagram},{label:"LinkedIn",href:siteConfig.social.linkedin,Icon:Linkedin}].filter(item=>item.href);
  return <footer className="site-footer"><div className="shell footer-grid"><div className="footer-brand"><p className="eyebrow">OngoleProperty.com</p><h2>Local knowledge. Professional property marketing.</h2><p>Serving Ongole &amp; Prakasam District since 2002.</p>{socials.length>0&&<div className="footer-social" aria-label="Social media">{socials.map(({label,href,Icon})=><a href={href} key={label} target="_blank" rel="noreferrer" aria-label={label}><Icon aria-hidden="true"/></a>)}</div>}</div><FooterLinks title="Property" links={propertyLinks}/><FooterLinks title="Services" links={serviceLinks}/><FooterLinks title="Company" links={companyLinks}/><FooterLinks legal title="Support & Legal" links={policyLinks}/><section className="footer-contact" aria-labelledby="footer-contact-heading"><h3 id="footer-contact-heading">Contact</h3><address><a href={siteConfig.phoneHref}><Phone aria-hidden="true"/>{siteConfig.phone}</a><a href={siteConfig.whatsappHref} target="_blank" rel="noreferrer"><MessageCircle aria-hidden="true"/>{siteConfig.whatsapp}</a><a href={`mailto:${siteConfig.email}`}><Mail aria-hidden="true"/><span>General Enquiry<br/>{siteConfig.email}</span></a><a href={`mailto:${siteConfig.salesEmail}`}><Mail aria-hidden="true"/><span>Sales &amp; Advertising<br/>{siteConfig.salesEmail}</span></a><a href={`mailto:${siteConfig.nriEmail}`}><Mail aria-hidden="true"/><span>NRI Services<br/>{siteConfig.nriEmail}</span></a><div><MapPinned aria-hidden="true"/><span><strong>Our Service Area</strong><br/>{siteConfig.serviceArea}<br/>Online Assistance · Field Visits</span></div></address></section></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} OngoleProperty.com. All rights reserved.</span><span>Serving Ongole &amp; Prakasam District</span></div></footer>;
}
