import type {Metadata} from "next";
import Link from "next/link";
import {CaptchaWidget} from "@/src/components/captcha-widget";
import {safeReturnPath} from "@/src/lib/auth/session";
import {PasswordInput} from "@/src/components/password-input";
export const metadata:Metadata={title:"Sign in",robots:{index:false,follow:false}};
const messages:Record<string,string>={invalid_credentials:"The email or password is incorrect.",email_not_confirmed:"Confirm your email address before signing in.",auth_unavailable:"Authentication is temporarily unavailable. Please try again.",account_inactive:"This account is not active. Contact support.",profile_unavailable:"Your account profile could not be loaded. Please try again.",confirmation_failed:"The confirmation link is invalid or expired. Request a new email.",session_missing:"The confirmation succeeded but no session was created. Please sign in.",recovery_session_missing:"Open the latest password-reset link from your email.",rate_limited:"Too many attempts. Please wait and try again."};
const notices:Record<string,string>={check_email:"Registration received. Confirm your email before signing in.",reset_sent:"If that account exists, a password-reset link has been sent.",password_updated:"Your password was updated successfully."};
export default async function LoginPage({searchParams}:{searchParams:Promise<{error?:string;notice?:string;returnTo?:string}>}){const query=await searchParams,returnTo=safeReturnPath(query.returnTo);return <main id="main" className="auth-page"><section className="auth-card"><p className="eyebrow">Welcome back</p><h1>Sign in to your account</h1><p>Manage draft property submissions, enquiries and your profile securely.</p>{query.error&&<p className="form-message error" role="alert">{messages[query.error]||"Sign-in failed. Please try again."}</p>}{query.notice&&<p className="form-message success" role="status">{notices[query.notice]||"Your request was completed."}</p>}<form className="oauth-form" action="/api/auth/google" method="post"><input type="hidden" name="returnTo" value={returnTo}/><button className="button button-light" type="submit">Continue with Google</button></form><div className="auth-divider"><span>or sign in with email</span></div><form action="/api/auth/login" method="post"><input type="hidden" name="returnTo" value={returnTo}/><label>Email<input required type="email" name="email" autoComplete="email" autoCapitalize="none"/></label><label>Password<PasswordInput autoComplete="current-password"/></label><CaptchaWidget/><button className="button" type="submit">Sign in</button></form><p><Link href="/forgot-password">Forgot your password?</Link></p><p>New to OngoleProperty.com? <Link href={`/register?returnTo=${encodeURIComponent(returnTo)}`}>Create a free account</Link></p></section></main>}
