import type {Metadata} from "next";
import Link from "next/link";
import {redirect} from "next/navigation";
import {BedDouble,Building2,ChartNoAxesCombined,CirclePlus,MessageSquare,Users} from "lucide-react";
import {ChartCard,DashboardShell,DataTable,EmptyState,PlanUsageCard,QuickActionCard,StatCard,StatusBadge} from "@/src/components/dashboard/dashboard-shell";
import {createSupabaseServerClient} from "@/src/lib/supabase/server";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"PG owner dashboard",robots:{index:false,follow:false}};
type PgRow={id:string;pg_name:string;category:string;rent_per_bed:number;property_id:string;properties:{status:string;reference_no:string;locality_text:string;updated_at:string}|{status:string;reference_no:string;locality_text:string;updated_at:string}[];pg_room_types:{id:string;capacity:number;available_beds:number;monthly_rent:number;sharing_type:string}[]};
export default async function PgDashboard(){
  const supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/login?returnTo=/dashboard/pg");
  const[{data:listings},{data:planContext}]=await Promise.all([supabase.from("pg_listings").select("id,pg_name,category,rent_per_bed,property_id,properties!inner(status,reference_no,locality_text,updated_at,owner_id,deleted_at),pg_room_types(id,capacity,available_beds,monthly_rent,sharing_type)").eq("properties.owner_id",auth.user.id).is("properties.deleted_at",null),supabase.rpc("get_my_plan_context")]);
  const pgs=(listings||[]) as unknown as PgRow[];const rooms=pgs.flatMap((item)=>item.pg_room_types||[]);const capacity=rooms.reduce((sum,room)=>sum+room.capacity,0),available=rooms.reduce((sum,room)=>sum+room.available_beds,0),occupied=Math.max(0,capacity-available);const occupancy=capacity?Math.round(occupied/capacity*100):0;
  const propertyIds=pgs.map((item)=>item.property_id);const start=new Date();start.setDate(start.getDate()-29);
  const[{count:enquiryCount},{data:analytics}]=await Promise.all([propertyIds.length?supabase.from("enquiries").select("id",{count:"exact",head:true}).in("property_id",propertyIds):Promise.resolve({count:0}),supabase.from("analytics_daily").select("day,event_count").eq("owner_id",auth.user.id).eq("entity_type","pg").eq("event_type","listing_view").gte("day",start.toISOString().slice(0,10))]);
  const plan=(planContext as {plan?:{name?:string;pg_listing_limit?:number};usage?:{pg_listings?:number}}|null)||{};const roomTypes=Object.entries(rooms.reduce<Record<string,number>>((acc,room)=>({...acc,[room.sharing_type]:(acc[room.sharing_type]||0)+1}),{}));const maxRoom=Math.max(1,...roomTypes.map(([,value])=>value));
  return <DashboardShell title="Paying Guest" description="Monitor PG listings, room inventory, availability and performance." actions={<Link className="button" href="/dashboard/pg/new">Add PG</Link>} breadcrumbs={[{label:"Dashboard",href:"/dashboard"},{label:"Paying Guest"}]}>
    <section className="dashboard-stat-grid"><StatCard label="Total PG listings" value={pgs.length} icon={<Building2/>}/><StatCard label="Draft PGs" value={pgs.filter((item)=>property(item).status==="draft").length} icon={<CirclePlus/>}/><StatCard label="Pending review" value={pgs.filter((item)=>property(item).status==="pending_review").length} icon={<Building2/>}/><StatCard label="Published PGs" value={pgs.filter((item)=>property(item).status==="published").length} icon={<Building2/>}/><StatCard label="Room types" value={rooms.length} icon={<BedDouble/>}/><StatCard label="Total beds" value={capacity} icon={<BedDouble/>}/><StatCard label="Available beds" value={available} change={`${occupancy}% occupied`} icon={<Users/>}/><StatCard label="Enquiries" value={enquiryCount||0} icon={<MessageSquare/>}/><StatCard label="Monthly views" value={(analytics||[]).reduce((sum,item)=>sum+Number(item.event_count),0)} icon={<ChartNoAxesCombined/>}/></section>
    <section className="dashboard-grid-main"><ChartCard title="Room type breakdown" description="Inventory distribution by sharing type"><div className="chart-bars">{roomTypes.length?roomTypes.map(([type,value])=><div key={type}><i style={{height:`${value/maxRoom*100}%`}}/><small>{type.replace("_"," ")}</small></div>):<EmptyState title="No rooms" description="Add room types to see inventory insights."/>}</div></ChartCard><PlanUsageCard plan={plan.plan?.name||"Free"} used={plan.usage?.pg_listings||pgs.length} limit={plan.plan?.pg_listing_limit||0} label="PG listings"/></section>
    <section className="dashboard-grid-2"><article className="dashboard-card"><header><h2>Quick actions</h2></header><div className="quick-action-grid"><QuickActionCard href="/dashboard/pg/new" title="Add PG" description="Create a new PG draft" icon={<Building2/>}/><QuickActionCard href={pgs[0]?`/dashboard/pg/${pgs[0].id}`:"/dashboard/pg/new"} title="Add Room Type" description="Update room inventory" icon={<BedDouble/>}/><QuickActionCard href={pgs[0]?`/dashboard/pg/${pgs[0].id}`:"/dashboard/pg/new"} title="Update Availability" description="Keep available beds current" icon={<Users/>}/><QuickActionCard href="/dashboard/enquiries" title="View Enquiries" description="Follow up with prospects" icon={<MessageSquare/>}/><QuickActionCard href="/pricing" title="Upgrade Plan" description="Increase PG listing limits" icon={<ChartNoAxesCombined/>}/></div></article><article className="dashboard-card"><header><h2>Inventory insight</h2></header><p><strong>{occupancy}%</strong> occupancy across {capacity} configured beds.</p>{rooms.length>0&&<p>Rent range: ₹{Math.min(...rooms.map((room)=>room.monthly_rent)).toLocaleString("en-IN")} – ₹{Math.max(...rooms.map((room)=>room.monthly_rent)).toLocaleString("en-IN")} per month.</p>}</article></section>
    <section className="dashboard-section"><div className="dashboard-section-head"><h2>PG listings</h2><span>{pgs.length} records</span></div>{pgs.length?<DataTable caption="PG owner listings" headers={["PG","Type","Location","Rooms","Beds","Status",""]}>{pgs.map((pg)=><tr key={pg.id}><td><strong>{pg.pg_name}</strong><br/><small>{property(pg).reference_no}</small></td><td>{pg.category.replaceAll("_"," ")}</td><td>{property(pg).locality_text}</td><td>{pg.pg_room_types.length}</td><td>{pg.pg_room_types.reduce((sum,room)=>sum+room.available_beds,0)} available</td><td><StatusBadge status={property(pg).status}/></td><td><Link href={`/dashboard/pg/${pg.id}`}>Manage</Link></td></tr>)}</DataTable>:<EmptyState title="No PG listings" description="Create your first PG and configure its rooms." action={<Link className="button" href="/dashboard/pg/new">Add PG</Link>}/>}</section>
  </DashboardShell>;
}
function property(pg:PgRow){return Array.isArray(pg.properties)?pg.properties[0]:pg.properties}
