import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {FileSearch,Handshake,MapPinned,SearchCheck,Send,ShieldCheck} from "lucide-react";
import {EnquiryForm} from "@/src/components/enquiry-form";
import {NriFaq,type NriFaqItem} from "@/src/components/nri-faq";
import {siteConfig} from "@/src/config/site";

const description="Professional NRI property assistance across Ongole and Prakasam District, including property search, site visits, local coordination, verification support, documentation and registration coordination.";
export const metadata:Metadata={title:"Professional NRI Property Services in Ongole & Prakasam District",description,alternates:{canonical:"/nri-services-ongole"},openGraph:{title:"Professional NRI Property Services in Ongole & Prakasam District",description,url:"/nri-services-ongole",type:"website",images:[{url:"/images/nri/nri-family-consultation.webp",width:1600,height:708,alt:"NRI family consulting online with a property professional"}]},twitter:{card:"summary_large_image",title:"Professional NRI Property Services in Ongole & Prakasam District",description,images:["/images/nri/nri-family-consultation.webp"]}};
const services=[
  [SearchCheck,"Property Search Assistance","Local property discovery based on your requirements."],[Handshake,"Property Buying & Selling Assistance","Professional coordination for buying, selling, renting, leasing and advertising."],[ShieldCheck,"Property Verification Support","Coordination with a reputed lawyer where verification is required."],[MapPinned,"Property Site Visit & Field Assistance","Local visits, relevant observations and updates when you cannot travel."],[FileSearch,"Documentation & Registration Coordination","Assistance organizing documents and coordinating registration steps and applicable document handover."],[Send,"Local & Online Property Coordination","Clear communication, follow-ups and local requirements while you are away from India."],
] as const;
const faqs:NriFaqItem[]=[
  {question:"Can you help trace an ancestral or old property?",answer:"We can assist using available documents, records and local property information. Results depend on the quality and availability of those sources, so no tracing or legal outcome is guaranteed."},
  {question:"Do I need to travel to India?",answer:"Not always. Many requirements can begin online, with local field assistance coordinated as needed. Travel or an authorised representative may still be required for particular legal or registration steps."},
  {question:"How are service charges determined?",answer:"Charges depend on the service type, property location, available records and scope of local work. The applicable scope and charges are discussed before work begins."},
  {question:"What documents should I share?",answer:"Share the property-related documents and reference information currently available. The team will identify what else may be needed for the requested coordination."},
  {question:"How long will the process take?",answer:"Duration varies with the property requirement, record availability, third-party response times and official processes. An appropriate estimate can be discussed after initial review."},
  {question:"Can you coordinate registration and document handover?",answer:"Yes. We can coordinate local communication and applicable registration steps, followed by secure handover of registered documents to the rightful owner or an authorised recipient."},
  {question:"How do I get started?",answer:"Submit the registration-free enquiry form or email nri@ongoleproperty.com with your property requirement."},
];

export default function NriServicesPage(){
  const structuredData=[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteConfig.url},{"@type":"ListItem",position:2,name:"NRI Services",item:`${siteConfig.url}/nri-services-ongole`}]},{"@context":"https://schema.org","@type":"Service",name:"Professional NRI Property Services",description,areaServed:["Ongole","Prakasam District"],provider:{"@type":"Organization",name:siteConfig.name,url:siteConfig.url},url:`${siteConfig.url}/nri-services-ongole`},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))}];
  return <main id="main" className="nri-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/>
    <section className="nri-hero"><div className="shell nri-hero-grid"><div><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><b>›</b><span>NRI Services</span></nav><p className="eyebrow">Trusted local coordination</p><h1>Professional NRI Property Services in Ongole &amp; Prakasam District</h1><h2>Professional property assistance for NRIs with local coordination across Ongole &amp; Prakasam District.</h2><p>We assist with buying, selling, renting, leasing, advertising and other property requirements through property search, site visits, local coordination, marketing, verification support, documentation, registration coordination and applicable document handover.</p><div className="button-row"><a className="button" href="#nri-enquiry">Discuss Your Property Requirement</a><a className="button button-outline" href={`mailto:${siteConfig.nriEmail}`}>Email Us: {siteConfig.nriEmail}</a></div></div><div className="nri-hero-image"><Image src="/images/nri/nri-family-consultation.webp" alt="NRI family consulting online with an OngoleProperty.com property professional" width={1600} height={708} priority sizes="(max-width: 900px) 100vw, 52vw"/></div></div></section>
    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">NRI assistance</p><h2>Services planned around your property requirement</h2></div><p>Concise, professional coordination for property requirements in Ongole and Prakasam District.</p></div><div className="nri-service-cards">{services.map(([Icon,title,copy])=><article key={title}><Icon aria-hidden="true"/><h3>{title}</h3><p>{copy}</p></article>)}<article><Handshake aria-hidden="true"/><h3>Other Property-Related Assistance</h3><p>Discuss requirements not covered above so the appropriate local assistance can be identified.</p></article></div></section>
    <section className="section section-tinted" id="property-tracing"><div className="shell tracing-grid"><div className="tracing-image"><Image src="/images/nri/property-tracing-survey.webp" alt="Survey team assisting with identification of a property boundary" width={1600} height={900} sizes="(max-width: 900px) 100vw, 45vw"/></div><div><p className="eyebrow">Featured unique service</p><h2>Exclusive Property Tracing Service</h2><p>Looking for an ancestral property or an old property whose location or boundaries are difficult to identify? We provide professional Property Tracing assistance using available documents, records and local property information.</p><p>Tracing results depend on the available evidence and local information; no legal result or successful identification is guaranteed.</p><a className="button" href="#nri-enquiry">Discuss a Property Tracing Requirement</a></div></div></section>
    <section className="section shell nri-process"><div className="section-heading"><div><p className="eyebrow">How it works</p><h2>A clear four-step process</h2></div></div><Image src="/images/nri/ongoleproperty-nri-property-services-process.png" alt="NRI property services process in Ongole and Prakasam District – online consultation, local assistance and successful execution" width={1536} height={1024} sizes="(max-width: 900px) 100vw, 1180px"/></section>
    <section className="section section-tinted nri-faq"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Helpful information</p><h2>Frequently Asked Questions</h2></div></div><NriFaq items={faqs}/></div></section>
    <section className="section shell nri-enquiry-layout" id="nri-enquiry"><div><p className="eyebrow">Registration-free enquiry</p><h2>Discuss Your Property Requirement</h2><p>Tell us what you need, and our team will coordinate with you regarding your property requirement in Ongole &amp; Prakasam District.</p><a href={`mailto:${siteConfig.nriEmail}`}>{siteConfig.nriEmail}</a><p className="service-area-note">We currently do not have a customer-facing physical office. Our NRI property services are coordinated online with professional local field assistance across Ongole and Prakasam District.</p></div><div className="contact-form-card"><EnquiryForm variant="nri" captchaSiteKey={process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY}/></div></section>
  </main>;
}
