const escape=(value:string)=>value.replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]||character));
export type EmailTemplate="property-approved"|"property-rejected"|"new-enquiry"|"welcome"|"password-reset";
export function emailTemplate(template:EmailTemplate,data:Record<string,string>){const name=escape(data.name||"Customer");const reference=escape(data.reference||"");const templates:Record<EmailTemplate,{subject:string;body:string}>={
  "property-approved":{subject:`Property ${reference} approved`,body:`<h1>Your property is approved</h1><p>Hello ${name}, your property <strong>${reference}</strong> has passed review and is ready for publication.</p>`},
  "property-rejected":{subject:`Update required for property ${reference}`,body:`<h1>Property review update</h1><p>Hello ${name}, property <strong>${reference}</strong> was not approved.</p><p>${escape(data.reason||"Please contact our property team for details.")}</p>`},
  "new-enquiry":{subject:`New enquiry ${reference}`,body:`<h1>New property enquiry</h1><p>${name} submitted enquiry <strong>${reference}</strong>.</p><p>${escape(data.message||"")}</p>`},
  welcome:{subject:"Welcome to OngoleProperty.com",body:`<h1>Welcome, ${name}</h1><p>Your account is ready. Property submissions stay private until manual approval.</p>`},
  "password-reset":{subject:"Reset your OngoleProperty.com password",body:`<h1>Password reset</h1><p>Hello ${name}, use the secure reset link sent by our authentication service. Ignore this message if you did not request it.</p>`}
};const content=templates[template];return{subject:content.subject,html:`<!doctype html><html><body style="font-family:Arial,sans-serif;color:#17211d"><div style="max-width:620px;margin:auto;padding:32px"><p style="color:#c96845;font-weight:700">ONGOLEPROPERTY.COM</p>${content.body}<hr><p style="color:#66736d;font-size:12px">Kosana Associates LLP · Ongole, Prakasam District</p></div></body></html>`,text:content.body.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}}
