import {createClient} from "@supabase/supabase-js";
try{process.loadEnvFile(".env.local")}catch{/* CI/Vercel may supply variables directly. */}
const required=["NEXT_PUBLIC_SITE_URL","NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_ANON_KEY","AUTH_TEST_USER_EMAIL","AUTH_TEST_USER_PASSWORD","AUTH_TEST_ADMIN_EMAIL","AUTH_TEST_ADMIN_PASSWORD"];
const missing=required.filter((key)=>!process.env[key]);if(missing.length){console.error(JSON.stringify({status:"FAIL",reason:"missing_environment",missing}));process.exit(2)}
const site=process.env.NEXT_PUBLIC_SITE_URL.replace(/\/$/,""),url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;const checks=[];
function pass(name){checks.push(name)}function fail(name){throw new Error(name)}
async function applicationLogin(email,password){const body=new URLSearchParams({email:email.trim().toLowerCase(),password,returnTo:"/dashboard"});const response=await fetch(`${site}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body,redirect:"manual"});if(response.status!==303)fail("application_login_status");const setCookies=response.headers.getSetCookie();if(!setCookies.length)fail("application_session_cookie_missing");const cookie=setCookies.map((value)=>value.split(";",1)[0]).join("; ");const contextResponse=await fetch(`${site}/api/auth/context`,{headers:{Cookie:cookie},redirect:"manual",cache:"no-store"});if(contextResponse.status!==200)fail("application_auth_context");const context=await contextResponse.json();const repeated=await fetch(`${site}/api/auth/context`,{headers:{Cookie:cookie},redirect:"manual",cache:"no-store"});if(repeated.status!==200)fail("application_session_persistence");return{context,cookie}}
try{
  const normal=await applicationLogin(process.env.AUTH_TEST_USER_EMAIL,process.env.AUTH_TEST_USER_PASSWORD);pass("normal_user_login");pass("normal_user_session_persistence");if(normal.context.user_id==null||normal.context.profile_status!=="active")fail("normal_profile_context");if(normal.context.permissions?.includes("roles.manage"))fail("normal_user_admin_isolation");pass("normal_profile_read");pass("normal_user_admin_isolation");
  const userClient=createClient(url,key,{auth:{persistSession:false}});const userLogin=await userClient.auth.signInWithPassword({email:process.env.AUTH_TEST_USER_EMAIL.trim().toLowerCase(),password:process.env.AUTH_TEST_USER_PASSWORD});if(userLogin.error||!userLogin.data.user)fail("normal_supabase_login");const ownProfile=await userClient.from("profiles").select("id,status").eq("id",userLogin.data.user.id).single();if(ownProfile.error||ownProfile.data.id!==userLogin.data.user.id)fail("normal_profile_ownership");const ownProperties=await userClient.from("properties").select("id").eq("owner_id",userLogin.data.user.id).limit(1);if(ownProperties.error)fail("owner_authorized_read");pass("owner_authorized_read");
  const admin=await applicationLogin(process.env.AUTH_TEST_ADMIN_EMAIL,process.env.AUTH_TEST_ADMIN_PASSWORD);pass("admin_login");const needed=["properties.read","properties.manage","enquiries.read","enquiries.manage","settings.manage","audit.read"];if(!needed.every((permission)=>admin.context.permissions?.includes(permission)))fail("admin_permission_resolution");pass("admin_permission_resolution");
  const adminClient=createClient(url,key,{auth:{persistSession:false}});const adminLogin=await adminClient.auth.signInWithPassword({email:process.env.AUTH_TEST_ADMIN_EMAIL.trim().toLowerCase(),password:process.env.AUTH_TEST_ADMIN_PASSWORD});if(adminLogin.error)fail("admin_supabase_login");const adminRead=await adminClient.from("properties").select("id",{count:"exact",head:true});if(adminRead.error)fail("admin_authorized_read");pass("admin_authorized_read");
  console.info(JSON.stringify({status:"PASS",checks},null,2));
}catch(error){console.error(JSON.stringify({status:"FAIL",failed:error instanceof Error?error.message:"unknown",passed:checks},null,2));process.exit(1)}
