import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { env } from "@/src/lib/env";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"My properties",robots:{index:false,follow:false}};
const filters=[{value:"",label:"All"},{value:"draft",label:"Drafts"},{value:"pending_review",label:"Pending"},{value:"approved",label:"Approved"},{value:"published",label:"Published"},{value:"rejected",label:"Rejected"},{value:"archived",label:"Archived"}];

export default async function DashboardPage({searchParams}:{searchParams:Promise<{created?:string;notice?:string;status?:string}>}){
  if(!env.isSupabaseConfigured)return <main id="main" className="portal-page"><div className="shell"><div className="config-warning"><h1>Dashboard configuration pending</h1><p>Add the Supabase environment values and apply the included migrations. Public demo mode remains available.</p></div></div></main>;
  const supabase=await createSupabaseServerClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/login?returnTo=/dashboard");const query=await searchParams;
  const [{data:profile},{data:isAdmin},{data:allProperties}]=await Promise.all([supabase.from("profiles").select("full_name,reference_no,account_type,status").eq("id",auth.user.id).single(),supabase.rpc("has_permission",{required_permission:"properties.read"}),supabase.from("properties").select("id,reference_no,title,status,updated_at,slug,locality_text,city_text,price_inr").eq("owner_id",auth.user.id).is("deleted_at",null).order("updated_at",{ascending:false})]);
  const selected=filters.some((item)=>item.value===query.status)?query.status||"":"";const properties=(allProperties||[]).filter((item)=>!selected||item.status===selected);const counts=Object.fromEntries(filters.slice(1).map((item)=>[item.value,(allProperties||[]).filter((property)=>property.status===item.value).length]));
  return <main id="main" className="portal-page"><div className="shell"><div className="portal-title"><div><p className="eyebrow">Owner dashboard</p><h1>Welcome, {profile?.full_name||auth.user.email}</h1><p>{profile?.reference_no} · {profile?.account_type} · {profile?.status}</p></div><div className="portal-actions">{isAdmin&&<Link className="button button-light" href="/admin">Admin panel</Link>}<Link className="button" href="/post-property">Add property</Link><form action="/api/auth/logout" method="post"><button className="text-button" type="submit">Sign out</button></form></div></div>
  {query.created&&<div className="success-notice">Draft {query.created} was created. Add media and submit it when complete.</div>}{query.notice==="deleted"&&<div className="success-notice">The property was archived and removed from your active workspace.</div>}
  <nav className="status-tabs" aria-label="Filter your properties">{filters.map((item)=><Link key={item.value||"all"} className={selected===item.value?"is-active":""} href={item.value?`/dashboard?status=${item.value}`:"/dashboard"}>{item.label}{item.value&&<span>{counts[item.value]||0}</span>}</Link>)}</nav>
  <section className="portal-section"><div className="section-heading compact"><div><p className="eyebrow">Your listings</p><h2>{selected?filters.find((item)=>item.value===selected)?.label:"All properties"}</h2></div><span>{properties.length} records</span></div>{properties.length?<div className="portal-list">{properties.map((property)=><article key={property.id}><div><span className={`status status-${property.status}`}>{property.status.replaceAll("_"," ")}</span><h3>{property.title}</h3><p>{property.reference_no} · {property.locality_text}, {property.city_text} · ₹{Number(property.price_inr||0).toLocaleString("en-IN")} · Updated {new Date(property.updated_at).toLocaleDateString("en-IN")}</p></div><Link href={`/dashboard/properties/${property.id}`}>Manage →</Link></article>)}</div>:<div className="empty-state"><h2>No matching properties</h2><p>Create a property or choose another status filter.</p><Link className="button" href="/post-property">Post a property</Link></div>}</section></div></main>;
}
