import{NextRequest,NextResponse}from"next/server";import ExcelJS from"exceljs";import{createSupabaseServerClient}from"@/src/lib/supabase/server";
const configs={
  users:{permission:"users.read",table:"profiles",columns:["reference_no","full_name","email","mobile","account_type","status","created_at"],status:true},
  properties:{permission:"properties.read",table:"properties",columns:["reference_no","title","status","transaction_type","locality_text","city_text","district_text","price_inr","is_verified","is_featured","published_at","created_at"],status:true},
  pg:{permission:"pg.read",table:"pg_listings",columns:["id","pg_name","category","rent_per_bed","capacity","food_type","created_at"],status:false},
  enquiries:{permission:"enquiries.read",table:"enquiries",columns:["reference_no","name","mobile","email","status","priority","source","follow_up_at","created_at"],status:true},
  subscriptions:{permission:"subscriptions.read",table:"subscriptions",columns:["id","user_id","plan_id","status","provider","starts_at","ends_at","renewal_at","created_at"],status:true,plan:true},
  payments:{permission:"payments.read",table:"payments",columns:["id","user_id","plan_id","provider","provider_payment_id","amount_inr","currency","payment_method","status","failure_reason","captured_at","created_at"],status:true,plan:true},
  revenue:{permission:"payments.read",table:"payments",columns:["id","user_id","plan_id","provider","amount_inr","currency","status","captured_at","created_at"],status:true,plan:true,forcedStatus:"captured"},
  promotions:{permission:"promotions.read",table:"promotion_activations",columns:["id","product_id","property_id","user_id","starts_at","ends_at","status","created_at"],status:true},
  advertisements:{permission:"settings.manage",table:"advertisements",columns:["id","title","placement","status","starts_at","ends_at","created_at"],status:true},
  approval_turnaround:{permission:"properties.read",table:"property_status_history",columns:["id","property_id","from_status","to_status","changed_by","reason","created_at"],status:false},
  geographic:{permission:"properties.read",table:"properties",columns:["reference_no","title","status","locality_text","city_text","district_text","state_text","created_at"],status:true}
}as const;
function safe(value:unknown){const text=value==null?"":typeof value==="object"?JSON.stringify(value):String(value);return/^[=+\-@\t\r]/.test(text)?`'${text}`:text}
export async function GET(request:NextRequest,{params}:{params:Promise<{entity:string}>}){const{entity}=await params;const config=configs[entity as keyof typeof configs];if(!config)return NextResponse.json({error:"Unknown report."},{status:404});const supabase=await createSupabaseServerClient();const{data:auth}=await supabase.auth.getUser();if(!auth.user)return NextResponse.json({error:"Authentication required."},{status:401});const[{data:reports},{data:module}]=await Promise.all([supabase.rpc("has_permission",{required_permission:"reports.read"}),supabase.rpc("has_permission",{required_permission:config.permission})]);if(!reports||!module)return NextResponse.json({error:"Permission denied."},{status:403});let query=supabase.from(config.table).select(config.columns.join(",")).limit(10000);const from=request.nextUrl.searchParams.get("from"),to=request.nextUrl.searchParams.get("to"),status=request.nextUrl.searchParams.get("status"),plan=request.nextUrl.searchParams.get("plan");if(from&&/^\d{4}-\d{2}-\d{2}$/.test(from))query=query.gte("created_at",`${from}T00:00:00Z`);if(to&&/^\d{4}-\d{2}-\d{2}$/.test(to))query=query.lt("created_at",`${to}T23:59:59.999Z`);if("forcedStatus"in config)query=query.eq("status",config.forcedStatus);else if("status"in config&&config.status&&status)query=query.eq("status",status.replace(/[^a-z_]/g,""));if("plan"in config&&config.plan&&plan&&/^[0-9a-f-]{36}$/i.test(plan))query=query.eq("plan_id",plan);const{data,error}=await query;if(error)return NextResponse.json({error:"Report query failed."},{status:500});const rows=(data||[])as unknown as Record<string,unknown>[],format=request.nextUrl.searchParams.get("format")==="xlsx"?"xlsx":"csv";await supabase.rpc("record_audit_event",{event_action:"report.export",event_type:entity,event_reference:format,event_new:{rows:rows.length,from,to,status,plan}});if(format==="csv"){const csv=[config.columns.join(","),...rows.map((row)=>config.columns.map((column)=>`"${safe(row[column]).replaceAll('"','""')}"`).join(","))].join("\r\n");return new NextResponse(`\uFEFF${csv}`,{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="ongoleproperty-${entity}.csv"`}})}const workbook=new ExcelJS.Workbook();workbook.creator="OngoleProperty.com";const sheet=workbook.addWorksheet(entity.slice(0,31));sheet.columns=config.columns.map((column)=>({header:column.replaceAll("_"," ").toUpperCase(),key:column,width:22}));rows.forEach((row)=>sheet.addRow(Object.fromEntries(config.columns.map((column)=>[column,safe(row[column])]))));sheet.getRow(1).font={bold:true};sheet.views=[{state:"frozen",ySplit:1}];const buffer=await workbook.xlsx.writeBuffer();return new NextResponse(new Uint8Array(buffer),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="ongoleproperty-${entity}.xlsx"`}})}
